#!/bin/sh
set -eu


HERE="$(cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)"
FIRESTAFF_DATA="${FIRESTAFF_DATA:-$HOME/.firestaff/data}"

GRAPHICS_DAT=${1:-$FIRESTAFF_DATA/GRAPHICS.DAT}
OUT_DIR=${2:-$HERE/roundtrip-matrix}
mkdir -p "$OUT_DIR"

python3 - <<'PY' "$GRAPHICS_DAT" "$OUT_DIR" "$HERE"
import re
import subprocess
import sys
from pathlib import Path

graphics_dat = sys.argv[1]
out_dir = Path(sys.argv[2])
here = Path(sys.argv[3])
runner = here / 'run_firestaff_m9_beta_harness.sh'

# Goal F round-trip sequences: activate → return-to-menu → navigate → re-activate
# Three lanes: f (sel=0), fn (sel=1), fnn (sel=2)
# r = return-to-menu event
seqs = [
    # Simple return-to-menu from each lane
    'far', 'fnar', 'fnnar',
    # Round-trip: activate, return, navigate, activate (different selection → REPEATED_VARIED)
    'farna', 'fnarna', 'fnnarna',
    # Round-trip with 2 navigations
    'farnna', 'fnarnna', 'fnnarnna',
    # Round-trip back to same selection (wraparound → REPEATED_SAME)
    'farnnna', 'fnarnnna', 'fnnarnnna',
    # Double round-trip: two returns, three activations
    'farnarnnna', 'fnarnarnnna', 'fnnarnarnnna',
    # Return with prior submenu hold: activate, frame-hold, return, navigate, activate
    'fafrna', 'fnafrna', 'fnnafrna',
    # Return with prior reactivate: activate, reactivate, return, navigate, activate
    'faarna', 'fnaarna', 'fnnaarna',
    # Return-to-menu in menu context (no-op, stays in menu)
    'fr', 'fnr', 'fnnr',
]

keys = [
    'finalSelectionIndex',
    'selectedRenderVariant',
    'activatedGraphicIndex',
    'finalScreen',
    'submenuEventCount',
    'submenuHoldAppliedCount',
    'submenuReactivateHandledCount',
    'lastSubmenuBehaviorClass',
    'submenuCumulativeBehaviorClass',
    'submenuBehaviorMask',
    'lastSubmenuBehaviorMask',
    'submenuFrameEventCount',
    'submenuIdleEventCount',
    'submenuAdvanceSuppressedCount',
    'submenuExitAppliedCount',
    'submenuExitMask',
    'submenuCumulativeExitClass',
    'submenuReturnExitCount',
    'submenuCancelExitCount',
    'lastSubmenuExitClass',
    'lastSubmenuExitMask',
    'selectionChangedCount',
    'renderVariantChangedCount',
    'activationCommittedCount',
    'enteredSubmenuCount',
    'gameStateMask',
    'gameStateCumulativeClass',
    'lastGameStateClass',
    'lastGameStateMask',
    'commitHistoryClass',
    'commitHistoryMask',
    'distinctCommittedSelections',
    'submenuReturnToMenuCount',
    'submenuRoundTripCount',
]

rows = []
for seq in seqs:
    prefix = out_dir / f'run_{seq}'
    p = subprocess.run(
        [str(runner), graphics_dat, str(prefix), '--unified-boot', seq],
        cwd=here,
        text=True,
        capture_output=True,
    )
    text = p.stdout + '\n' + p.stderr
    row = {'seq': seq, 'rc': str(p.returncode)}
    for key in keys:
        m = re.search(rf'{key}=([^\n]+)', text)
        row[key] = m.group(1).strip() if m else ''
    rows.append(row)

md = []
md.append('# ReDMCSB M10 round-trip matrix probe\n')
md.append('\n')
md.append('Generated by `run_firestaff_m10_roundtrip_matrix.sh`.\n')
md.append('\n')
header_cols = '| seq | rc | ' + ' | '.join(keys) + ' |\n'
sep_cols = '| --- | --- | ' + ' | '.join(['---'] * len(keys)) + ' |\n'
md.append(header_cols)
md.append(sep_cols)
for r in rows:
    cols = ' | '.join(r.get(k, '') for k in keys)
    md.append(f"| {r['seq']} | {r['rc']} | {cols} |\n")

# invariant checks
failures = []
def get(seq):
    for row in rows:
        if row['seq'] == seq:
            return row
    raise KeyError(seq)

def expect_same_pattern(label, seqs_list, pattern_keys):
    base = None
    for seq in seqs_list:
        row = get(seq)
        pattern = tuple(row[k] for k in pattern_keys)
        if base is None:
            base = pattern
        elif pattern != base:
            failures.append(f"{label}: {seq} has pattern {pattern}, expected {base}")

roundtrip_pattern_keys = [
    'commitHistoryClass', 'commitHistoryMask', 'distinctCommittedSelections',
    'enteredSubmenuCount', 'submenuReturnToMenuCount', 'submenuRoundTripCount',
    'activationCommittedCount',
]

# All round-trip sequences must have rc=0
for row in rows:
    if row['rc'] != '0':
        failures.append(f"rc: {row['seq']} has rc={row['rc']}, expected 0")

# Simple return-to-menu: screen goes back to MENU
for seq in ('far', 'fnar', 'fnnar'):
    row = get(seq)
    if row['finalScreen'] != '0':
        failures.append(f"return-to-menu finalScreen: {seq} has {row['finalScreen']}, expected 0 (MENU)")
    if row['submenuReturnToMenuCount'] != '1':
        failures.append(f"return-to-menu count: {seq} has {row['submenuReturnToMenuCount']}, expected 1")
    if row['commitHistoryClass'] != '1':
        failures.append(f"return-to-menu commit history: {seq} has {row['commitHistoryClass']}, expected 1 (SINGLE)")

expect_same_pattern('simple return-to-menu', ['far', 'fnar', 'fnnar'], roundtrip_pattern_keys)

# Return-to-menu in menu context = no-op
for seq in ('fr', 'fnr', 'fnnr'):
    row = get(seq)
    if row['submenuReturnToMenuCount'] != '0':
        failures.append(f"menu-context return: {seq} has returnToMenuCount={row['submenuReturnToMenuCount']}, expected 0")
    if row['commitHistoryClass'] != '0':
        failures.append(f"menu-context return commit: {seq} has {row['commitHistoryClass']}, expected 0 (NONE)")

# REPEATED_VARIED: round-trip to different selection
# farna: sel=0 → submenu → menu → sel=1 → submenu (different selection)
for seq in ('farna', 'fnarna', 'fnnarna'):
    row = get(seq)
    if row['commitHistoryClass'] != '3':
        failures.append(f"REPEATED_VARIED: {seq} has commitHistoryClass={row['commitHistoryClass']}, expected 3")
    if row['commitHistoryMask'] != '7':
        failures.append(f"REPEATED_VARIED mask: {seq} has commitHistoryMask={row['commitHistoryMask']}, expected 7")
    if row['distinctCommittedSelections'] != '2':
        failures.append(f"REPEATED_VARIED distinct: {seq} has {row['distinctCommittedSelections']}, expected 2")
    if row['enteredSubmenuCount'] != '2':
        failures.append(f"REPEATED_VARIED enteredSubmenu: {seq} has {row['enteredSubmenuCount']}, expected 2")
    if row['submenuRoundTripCount'] != '1':
        failures.append(f"REPEATED_VARIED roundTrip: {seq} has {row['submenuRoundTripCount']}, expected 1")

expect_same_pattern('single round-trip VARIED', ['farna', 'fnarna', 'fnnarna'], roundtrip_pattern_keys)

# 2-navigation round-trip: still REPEATED_VARIED
for seq in ('farnna', 'fnarnna', 'fnnarnna'):
    row = get(seq)
    if row['commitHistoryClass'] != '3':
        failures.append(f"2-nav REPEATED_VARIED: {seq} has commitHistoryClass={row['commitHistoryClass']}, expected 3")
    if row['distinctCommittedSelections'] != '2':
        failures.append(f"2-nav distinct: {seq} has {row['distinctCommittedSelections']}, expected 2")

expect_same_pattern('2-nav round-trip VARIED', ['farnna', 'fnarnna', 'fnnarnna'], roundtrip_pattern_keys)

# Wraparound round-trip: REPEATED_SAME (back to same selection via 3 advances)
for seq in ('farnnna', 'fnarnnna', 'fnnarnnna'):
    row = get(seq)
    if row['commitHistoryClass'] != '2':
        failures.append(f"wraparound REPEATED_SAME: {seq} has commitHistoryClass={row['commitHistoryClass']}, expected 2")
    if row['commitHistoryMask'] != '3':
        failures.append(f"wraparound mask: {seq} has commitHistoryMask={row['commitHistoryMask']}, expected 3")
    if row['distinctCommittedSelections'] != '1':
        failures.append(f"wraparound distinct: {seq} has {row['distinctCommittedSelections']}, expected 1")

expect_same_pattern('wraparound REPEATED_SAME', ['farnnna', 'fnarnnna', 'fnnarnnna'], roundtrip_pattern_keys)

# Double round-trip: 3 activations, first and last same selection, middle different
for seq in ('farnarnnna', 'fnarnarnnna', 'fnnarnarnnna'):
    row = get(seq)
    if row['commitHistoryClass'] != '3':
        failures.append(f"double round-trip: {seq} has commitHistoryClass={row['commitHistoryClass']}, expected 3")
    if row['enteredSubmenuCount'] != '3':
        failures.append(f"double round-trip enteredSubmenu: {seq} has {row['enteredSubmenuCount']}, expected 3")
    if row['submenuRoundTripCount'] != '2':
        failures.append(f"double round-trip roundTrip: {seq} has {row['submenuRoundTripCount']}, expected 2")
    if row['activationCommittedCount'] != '3':
        failures.append(f"double round-trip commits: {seq} has {row['activationCommittedCount']}, expected 3")

expect_same_pattern('double round-trip', ['farnarnnna', 'fnarnarnnna', 'fnnarnarnnna'], roundtrip_pattern_keys)

# Return with prior submenu hold, then navigate to different selection
for seq in ('fafrna', 'fnafrna', 'fnnafrna'):
    row = get(seq)
    if row['commitHistoryClass'] != '3':
        failures.append(f"hold+return VARIED: {seq} has commitHistoryClass={row['commitHistoryClass']}, expected 3")

expect_same_pattern('hold+return round-trip', ['fafrna', 'fnafrna', 'fnnafrna'], roundtrip_pattern_keys)

# Return with prior reactivate
for seq in ('faarna', 'fnaarna', 'fnnaarna'):
    row = get(seq)
    if row['commitHistoryClass'] != '3':
        failures.append(f"reactivate+return VARIED: {seq} has commitHistoryClass={row['commitHistoryClass']}, expected 3")
    if row['activationCommittedCount'] != '3':
        failures.append(f"reactivate+return commits: {seq} has {row['activationCommittedCount']}, expected 3")

expect_same_pattern('reactivate+return round-trip', ['faarna', 'fnaarna', 'fnnaarna'], roundtrip_pattern_keys)

# activationCommittedCount must match 'a' count
for row in rows:
    seq = row['seq']
    expected = str(seq.count('a'))
    value = row['activationCommittedCount']
    if value != expected:
        failures.append(f"activation commit count: {seq} has {value}, expected {expected}")

inv = []
inv.append('# ReDMCSB M10 round-trip matrix invariants\n')
inv.append('\n')
if failures:
    inv.append('Status: FAIL\n\n')
    for item in failures:
        inv.append(f'- {item}\n')
else:
    inv.append('Status: PASS\n\n')
    inv.append('- All round-trip sequences complete with rc=0\n')
    inv.append('- Simple return-to-menu (far/fnar/fnnar) transitions screen back to MENU, commitHistory=SINGLE\n')
    inv.append('- Return-to-menu in menu context (fr/fnr/fnnr) is no-op, commitHistory=NONE\n')
    inv.append('- Single-navigation round-trip (farna/fnarna/fnnarna) produces REPEATED_VARIED (class=3, mask=7, distinct=2)\n')
    inv.append('- Double-navigation round-trip (farnna/fnarnna/fnnarnna) also REPEATED_VARIED\n')
    inv.append('- Wraparound round-trip (farnnna/...) produces REPEATED_SAME (class=2, mask=3, distinct=1)\n')
    inv.append('- Double round-trip (farnarnnna/...) has 3 activations, 3 enteredSubmenu, 2 roundTrips, REPEATED_VARIED\n')
    inv.append('- Hold+return and reactivate+return round-trips produce REPEATED_VARIED\n')
    inv.append('- Cross-lane patterns are consistent across f/fn/fnn lanes\n')
    inv.append('- activationCommittedCount matches number of a events in every sequence\n')

(out_dir / 'roundtrip_matrix.md').write_text(''.join(md), encoding='utf-8')
(out_dir / 'roundtrip_invariants.md').write_text(''.join(inv), encoding='utf-8')
print(out_dir / 'roundtrip_matrix.md')
print(out_dir / 'roundtrip_invariants.md')
if failures:
    raise SystemExit(1)
PY
