#ifndef ACTION_AREA_NAME_ROUTES_PC34_COMPAT_H
#define ACTION_AREA_NAME_ROUTES_PC34_COMPAT_H
const char* action_area_name_routes_GetEvidence(void);
unsigned int action_area_name_routes_GetInvariant(void);
#endif
