#ifndef ACTION_AREA_ICON_ROUTES_PC34_COMPAT_H
#define ACTION_AREA_ICON_ROUTES_PC34_COMPAT_H
const char* action_area_icon_routes_GetEvidence(void);
unsigned int action_area_icon_routes_GetInvariant(void);
#endif
