#!/bin/sh
set -eu

# run_firestaff_m11_verify.sh
#
# M11 verify driver. Runs each implemented M11 phase probe in sequence.
# Separate from run_firestaff_m10_verify.sh so the M10 invariant
# (bit-identical final-hash after 100 ticks) cannot be disturbed by
# evolving M11 tooling.

HERE="$(cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)"
OUT_DIR=${1:-$HERE/verification-m11}
mkdir -p "$OUT_DIR"

SUMMARY_MD="$OUT_DIR/verification_summary.md"
{
    echo "# M11 verification summary"
    echo
    echo "Generated by run_firestaff_m11_verify.sh"
    echo
} > "$SUMMARY_MD"

# Phase A — SDL window + basic framebuffer
echo "=== Phase A: SDL window + framebuffer ==="
"$HERE/run_firestaff_m11_phase_a_probe.sh" "$OUT_DIR/phase-a" > \
    "$OUT_DIR/phase_a.log" 2>&1 || {
    echo "FAIL: Phase A probe did not pass"
    echo "see: $OUT_DIR/phase_a.log"
    {
        echo
        echo "## Phase A: FAIL"
        echo
        tail -n 30 "$OUT_DIR/phase_a.log" || true
    } >> "$SUMMARY_MD"
    exit 1
}
echo "Phase A: PASS"
{
    echo
    echo "## Phase A: PASS"
    echo
    grep '^PASS\|^FAIL\|^# summary' "$OUT_DIR/phase-a/phase_a_probe.log" || true
} >> "$SUMMARY_MD"

echo "=== Game view slice probe ==="
"$HERE/run_firestaff_m11_game_view_probe.sh" "$OUT_DIR/game-view" > \
    "$OUT_DIR/game_view.log" 2>&1 || {
    echo "FAIL: Game view probe did not pass"
    echo "see: $OUT_DIR/game_view.log"
    {
        echo
        echo "## Game view slice: FAIL"
        echo
        tail -n 30 "$OUT_DIR/game_view.log" || true
    } >> "$SUMMARY_MD"
    exit 1
}
echo "Game view slice: PASS"
{
    echo
    echo "## Game view slice: PASS"
    echo
    grep '^PASS\|^FAIL\|^# summary' "$OUT_DIR/game-view/game_view_probe.log" || true
} >> "$SUMMARY_MD"

echo "=== M11 verification complete ==="
printf '%s\n' "$SUMMARY_MD"
