#!/bin/sh
set -eu


HERE="$(cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)"
FIRESTAFF_DATA="${FIRESTAFF_DATA:-$HOME/.firestaff/data}"

GRAPHICS_DAT=${1:-$FIRESTAFF_DATA/GRAPHICS.DAT}
OUT_DIR=${2:-$HERE/submenu-matrix}
mkdir -p "$OUT_DIR"

python3 - <<'PY' "$GRAPHICS_DAT" "$OUT_DIR" "$HERE"
import re
import subprocess
import sys
from pathlib import Path

graphics_dat = sys.argv[1]
out_dir = Path(sys.argv[2])
here = Path(sys.argv[3])
runner = here / 'run_firestaff_m9_beta_harness.sh'

seqs = [
    'f', 'fn', 'fnn', 'fnnn',
    'fa', 'faa', 'faaa', 'faaaa',
    'faf', 'fai', 'fan', 'fann', 'fanan',
    'faaf', 'faai', 'faan',
    'faaifn',
    'fab', 'fac', 'fabc', 'facb',
    'fna', 'fnaa', 'fnaaa', 'fnaaaa',
    'fnaf', 'fnai', 'fnan', 'fnann', 'fnanan',
    'fnaaf', 'fnaai', 'fnaan', 'fnaaifn',
    'fnab', 'fnac', 'fnabc', 'fnacb',
    'fnna', 'fnnaa', 'fnnaaa', 'fnnaaaa',
    'fnnaf', 'fnnai', 'fnnan', 'fnnann', 'fnnanan',
    'fnnaaf', 'fnnaai', 'fnnaan', 'fnnaaifn',
    'fnnab', 'fnnac', 'fnnabc', 'fnnacb'
]
keys = [
    'finalSelectionIndex',
    'selectedRenderVariant',
    'activatedGraphicIndex',
    'finalScreen',
    'submenuEventCount',
    'submenuHoldAppliedCount',
    'submenuReactivateHandledCount',
    'lastSubmenuBehaviorClass',
    'submenuCumulativeBehaviorClass',
    'submenuBehaviorMask',
    'lastSubmenuBehaviorMask',
    'submenuFrameEventCount',
    'submenuIdleEventCount',
    'submenuAdvanceSuppressedCount',
    'submenuExitAppliedCount',
    'submenuExitMask',
    'submenuCumulativeExitClass',
    'submenuReturnExitCount',
    'submenuCancelExitCount',
    'lastSubmenuExitClass',
    'lastSubmenuExitMask',
    'selectionChangedCount',
    'renderVariantChangedCount',
    'activationCommittedCount',
    'enteredSubmenuCount',
    'gameStateMask',
    'gameStateCumulativeClass',
    'lastGameStateClass',
    'lastGameStateMask',
    'commitHistoryClass',
    'commitHistoryMask',
    'distinctCommittedSelections',
]
rows = []
for seq in seqs:
    prefix = out_dir / f'run_{seq}'
    p = subprocess.run(
        [str(runner), graphics_dat, str(prefix), '--unified-boot', seq],
        cwd=here,
        text=True,
        capture_output=True,
    )
    text = p.stdout + '\n' + p.stderr
    row = {'seq': seq, 'rc': str(p.returncode)}
    for key in keys:
        m = re.search(rf'{key}=([^\n]+)', text)
        row[key] = m.group(1).strip() if m else ''
    rows.append(row)

md = []
md.append('# ReDMCSB M9 submenu matrix probe\n')
md.append('\n')
md.append('Generated by `run_firestaff_m9_submenu_matrix.sh`.\n')
md.append('\n')
md.append('| seq | rc | finalSelectionIndex | selectedRenderVariant | activatedGraphicIndex | finalScreen | submenuEventCount | hold | reactivate | last behavior class | sequence behavior class | cumulative behavior mask | behavior mask | frame | idle | suppressed advance | exit applied | exit mask | cumulative exit class | return | cancel | last exit class | last exit mask | commitHistoryClass | commitHistoryMask | distinctCommitted |\n')
md.append('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n')
for r in rows:
    md.append(
        f"| {r['seq']} | {r['rc']} | {r['finalSelectionIndex']} | {r['selectedRenderVariant']} | {r['activatedGraphicIndex']} | {r['finalScreen']} | {r['submenuEventCount']} | {r['submenuHoldAppliedCount']} | {r['submenuReactivateHandledCount']} | {r['lastSubmenuBehaviorClass']} | {r['submenuCumulativeBehaviorClass']} | {r['submenuBehaviorMask']} | {r['lastSubmenuBehaviorMask']} | {r['submenuFrameEventCount']} | {r['submenuIdleEventCount']} | {r['submenuAdvanceSuppressedCount']} | {r['submenuExitAppliedCount']} | {r['submenuExitMask']} | {r['submenuCumulativeExitClass']} | {r['submenuReturnExitCount']} | {r['submenuCancelExitCount']} | {r['lastSubmenuExitClass']} | {r['lastSubmenuExitMask']} | {r['commitHistoryClass']} | {r['commitHistoryMask']} | {r['distinctCommittedSelections']} |\n"
    )

# invariant checks across the three current lanes
failures = []
def get(seq):
    for row in rows:
        if row['seq'] == seq:
            return row
    raise KeyError(seq)

def expect_same_pattern(label, seqs):
    base = None
    for seq in seqs:
        row = get(seq)
        pattern = (
            row['submenuEventCount'],
            row['submenuHoldAppliedCount'],
            row['submenuReactivateHandledCount'],
            row['lastSubmenuBehaviorClass'],
            row['submenuBehaviorMask'],
            row['submenuFrameEventCount'],
            row['submenuIdleEventCount'],
            row['submenuAdvanceSuppressedCount'],
            row['submenuExitAppliedCount'],
            row['submenuExitMask'],
            row['submenuCumulativeExitClass'],
            row['submenuReturnExitCount'],
            row['submenuCancelExitCount'],
            row['lastSubmenuExitClass'],
            row['lastSubmenuExitMask'],
        )
        if base is None:
            base = pattern
        elif pattern != base:
            failures.append(f"{label}: {seq} has pattern {pattern}, expected {base}")

expect_same_pattern('pre-activation menu baseline', ['f', 'fnnn'])

expect_same_pattern('first activation', ['fa', 'fna', 'fnna'])
expect_same_pattern('reactivate', ['faa', 'fnaa', 'fnnaa'])
expect_same_pattern('frame hold', ['faf', 'fnaf', 'fnnaf'])
expect_same_pattern('idle hold', ['fai', 'fnai', 'fnnai'])
expect_same_pattern('suppressed advance hold', ['fan', 'fnan', 'fnnan'])
expect_same_pattern('reactivate+frame', ['faaf', 'fnaaf', 'fnnaaf'])
expect_same_pattern('reactivate+idle', ['faai', 'fnaai', 'fnnaai'])
expect_same_pattern('reactivate+suppressed advance', ['faan', 'fnaan', 'fnnaan'])
expect_same_pattern('mixed long row', ['faaifn', 'fnaaifn', 'fnnaaifn'])
expect_same_pattern('triple return', ['faaa', 'fnaaa', 'fnnaaa'])
expect_same_pattern('quadruple return', ['faaaa', 'fnaaaa', 'fnnaaaa'])
expect_same_pattern('double cancel', ['fann', 'fnann', 'fnnann'])
expect_same_pattern('cancel-return-cancel', ['fanan', 'fnanan', 'fnnanan'])
expect_same_pattern('explicit back', ['fab', 'fnab', 'fnnab'])
expect_same_pattern('explicit cancel', ['fac', 'fnac', 'fnnac'])
expect_same_pattern('back then cancel', ['fabc', 'fnabc', 'fnnabc'])
expect_same_pattern('cancel then back', ['facb', 'fnacb', 'fnnacb'])

# game-state consequence invariants
# classes: 0=NONE, 1=NAVIGATED, 2=ACTIVATED, 3=ENTERED_SUBMENU, 4=HELD
# f alone reports HELD. fn/fnn advance the menu (NAVIGATED).
# Any row that enters the submenu via `a` reports cumulative ENTERED_SUBMENU.
game_state_cumulative_expectations = {
    'f': '4', 'fn': '1', 'fnn': '1', 'fnnn': '1',
}
for seq in (
    'fa', 'faa', 'faaa', 'faaaa', 'faf', 'fai', 'fan', 'fann', 'fanan',
    'faaf', 'faai', 'faan', 'faaifn',
    'fab', 'fac', 'fabc', 'facb',
    'fna', 'fnaa', 'fnaaa', 'fnaaaa', 'fnaf', 'fnai', 'fnan', 'fnann', 'fnanan',
    'fnaaf', 'fnaai', 'fnaan', 'fnaaifn',
    'fnab', 'fnac', 'fnabc', 'fnacb',
    'fnna', 'fnnaa', 'fnnaaa', 'fnnaaaa', 'fnnaf', 'fnnai', 'fnnan', 'fnnann', 'fnnanan',
    'fnnaaf', 'fnnaai', 'fnnaan', 'fnnaaifn',
    'fnnab', 'fnnac', 'fnnabc', 'fnnacb',
):
    game_state_cumulative_expectations[seq] = '3'
for seq, expected in game_state_cumulative_expectations.items():
    row = get(seq)
    value = row['gameStateCumulativeClass']
    if value != expected:
        failures.append(
            f"game state cumulative class: {seq} has {value}, expected {expected}"
        )

# activation commit counts must match the number of 'a' events in each seq
for row in rows:
    seq = row['seq']
    expected = str(seq.count('a'))
    value = row['activationCommittedCount']
    if value != expected:
        failures.append(
            f"activation commit count: {seq} has {value}, expected {expected}"
        )

# only the first 'a' after MENU should increment enteredSubmenuCount; any seq
# with at least one 'a' enters submenu exactly once, zero otherwise.
for row in rows:
    seq = row['seq']
    expected = '1' if 'a' in seq else '0'
    value = row['enteredSubmenuCount']
    if value != expected:
        failures.append(
            f"entered submenu count: {seq} has {value}, expected {expected}"
        )

# held-only rows (no navigation, no activation) keep gameStateMask == HELD=16.
# For 'f' alone, that is the only row without n or a.
held_only_rows = ['f']
for seq in held_only_rows:
    row = get(seq)
    if row['gameStateMask'] != '16':
        failures.append(
            f"held-only game state mask: {seq} has {row['gameStateMask']}, expected 16"
        )

# explicit behavior-class invariants
behavior_expectations = {
    'fa': '0', 'fna': '0', 'fnna': '0',
    'faa': '1', 'fnaa': '1', 'fnnaa': '1',
    'faaa': '1', 'fnaaa': '1', 'fnnaaa': '1',
    'faaaa': '1', 'fnaaaa': '1', 'fnnaaaa': '1',
    'faf': '2', 'fnaf': '2', 'fnnaf': '2',
    'fai': '3', 'fnai': '3', 'fnnai': '3',
    'fan': '4', 'fnan': '4', 'fnnan': '4',
    'fann': '4', 'fnann': '4', 'fnnann': '4',
    'fanan': '4', 'fnanan': '4', 'fnnanan': '4',
    'faaf': '2', 'fnaaf': '2', 'fnnaaf': '2',
    'faai': '3', 'fnaai': '3', 'fnnaai': '3',
    'faan': '4', 'fnaan': '4', 'fnnaan': '4',
    'faaifn': '4', 'fnaaifn': '4', 'fnnaaifn': '4',
    'fab': '6', 'fnab': '6', 'fnnab': '6',
    'fac': '7', 'fnac': '7', 'fnnac': '7',
    'fabc': '7', 'fnabc': '7', 'fnnabc': '7',
    'facb': '6', 'fnacb': '6', 'fnnacb': '6',
}
for seq, expected in behavior_expectations.items():
    row = get(seq)
    value = row['lastSubmenuBehaviorClass']
    if value != expected:
        failures.append(
            f"behavior class: {seq} has {value}, expected {expected}"
        )

cumulative_behavior_class_expectations = {
    'fa': '0', 'fna': '0', 'fnna': '0',
    'faa': '1', 'fnaa': '1', 'fnnaa': '1',
    'faaa': '1', 'fnaaa': '1', 'fnnaaa': '1',
    'faaaa': '1', 'fnaaaa': '1', 'fnnaaaa': '1',
    'faf': '2', 'fnaf': '2', 'fnnaf': '2',
    'fai': '3', 'fnai': '3', 'fnnai': '3',
    'fan': '4', 'fnan': '4', 'fnnan': '4',
    'fann': '4', 'fnann': '4', 'fnnann': '4',
    'fanan': '5', 'fnanan': '5', 'fnnanan': '5',
    'faaf': '5', 'fnaaf': '5', 'fnnaaf': '5',
    'faai': '5', 'fnaai': '5', 'fnnaai': '5',
    'faan': '5', 'fnaan': '5', 'fnnaan': '5',
    'faaifn': '5', 'fnaaifn': '5', 'fnnaaifn': '5',
    'fab': '6', 'fnab': '6', 'fnnab': '6',
    'fac': '7', 'fnac': '7', 'fnnac': '7',
    'fabc': '5', 'fnabc': '5', 'fnnabc': '5',
    'facb': '5', 'fnacb': '5', 'fnnacb': '5',
}
for seq, expected in cumulative_behavior_class_expectations.items():
    row = get(seq)
    value = row['submenuCumulativeBehaviorClass']
    if value != expected:
        failures.append(
            f"cumulative behavior class: {seq} has {value}, expected {expected}"
        )

behavior_mask_expectations = {
    'fa': '0', 'fna': '0', 'fnna': '0',
    'faa': '1', 'fnaa': '1', 'fnnaa': '1',
    'faaa': '1', 'fnaaa': '1', 'fnnaaa': '1',
    'faaaa': '1', 'fnaaaa': '1', 'fnnaaaa': '1',
    'faf': '2', 'fnaf': '2', 'fnnaf': '2',
    'fai': '4', 'fnai': '4', 'fnnai': '4',
    'fan': '8', 'fnan': '8', 'fnnan': '8',
    'fann': '8', 'fnann': '8', 'fnnann': '8',
    'fanan': '9', 'fnanan': '9', 'fnnanan': '9',
    'faaf': '3', 'fnaaf': '3', 'fnnaaf': '3',
    'faai': '5', 'fnaai': '5', 'fnnaai': '5',
    'faan': '9', 'fnaan': '9', 'fnnaan': '9',
    'faaifn': '15', 'fnaaifn': '15', 'fnnaaifn': '15',
    'fab': '16', 'fnab': '16', 'fnnab': '16',
    'fac': '32', 'fnac': '32', 'fnnac': '32',
    'fabc': '48', 'fnabc': '48', 'fnnabc': '48',
    'facb': '48', 'fnacb': '48', 'fnnacb': '48',
}
for seq, expected in behavior_mask_expectations.items():
    row = get(seq)
    value = row['submenuBehaviorMask']
    if value != expected:
        failures.append(
            f"behavior mask: {seq} has {value}, expected {expected}"
        )

# submenu exit semantic invariants (return/cancel/mixed/none)
# exit classes: 0=NONE, 1=RETURN, 2=CANCEL, 3=MIXED
# pre-activation rows and first-activation rows never enter submenu events,
# so they must stay NONE.
exit_class_expectations = {
    'f': '0', 'fn': '0', 'fnn': '0', 'fnnn': '0',
    'fa': '0', 'fna': '0', 'fnna': '0',
    'faa': '1', 'fnaa': '1', 'fnnaa': '1',
    'faaa': '1', 'fnaaa': '1', 'fnnaaa': '1',
    'faaaa': '1', 'fnaaaa': '1', 'fnnaaaa': '1',
    'faf': '0', 'fnaf': '0', 'fnnaf': '0',
    'fai': '0', 'fnai': '0', 'fnnai': '0',
    'fan': '2', 'fnan': '2', 'fnnan': '2',
    'fann': '2', 'fnann': '2', 'fnnann': '2',
    'fanan': '3', 'fnanan': '3', 'fnnanan': '3',
    'faaf': '1', 'fnaaf': '1', 'fnnaaf': '1',
    'faai': '1', 'fnaai': '1', 'fnnaai': '1',
    'faan': '3', 'fnaan': '3', 'fnnaan': '3',
    'faaifn': '3', 'fnaaifn': '3', 'fnnaaifn': '3',
    'fab': '1', 'fnab': '1', 'fnnab': '1',
    'fac': '2', 'fnac': '2', 'fnnac': '2',
    'fabc': '3', 'fnabc': '3', 'fnnabc': '3',
    'facb': '3', 'fnacb': '3', 'fnnacb': '3',
}
for seq, expected in exit_class_expectations.items():
    row = get(seq)
    value = row['submenuCumulativeExitClass']
    if value != expected:
        failures.append(
            f"cumulative exit class: {seq} has {value}, expected {expected}"
        )

exit_mask_expectations = {
    'f': '0', 'fn': '0', 'fnn': '0', 'fnnn': '0',
    'fa': '0', 'fna': '0', 'fnna': '0',
    'faa': '1', 'fnaa': '1', 'fnnaa': '1',
    'faaa': '1', 'fnaaa': '1', 'fnnaaa': '1',
    'faaaa': '1', 'fnaaaa': '1', 'fnnaaaa': '1',
    'faf': '0', 'fnaf': '0', 'fnnaf': '0',
    'fai': '0', 'fnai': '0', 'fnnai': '0',
    'fan': '2', 'fnan': '2', 'fnnan': '2',
    'fann': '2', 'fnann': '2', 'fnnann': '2',
    'fanan': '3', 'fnanan': '3', 'fnnanan': '3',
    'faaf': '1', 'fnaaf': '1', 'fnnaaf': '1',
    'faai': '1', 'fnaai': '1', 'fnnaai': '1',
    'faan': '3', 'fnaan': '3', 'fnnaan': '3',
    'faaifn': '3', 'fnaaifn': '3', 'fnnaaifn': '3',
    'fab': '1', 'fnab': '1', 'fnnab': '1',
    'fac': '2', 'fnac': '2', 'fnnac': '2',
    'fabc': '3', 'fnabc': '3', 'fnnabc': '3',
    'facb': '3', 'fnacb': '3', 'fnnacb': '3',
}
for seq, expected in exit_mask_expectations.items():
    row = get(seq)
    value = row['submenuExitMask']
    if value != expected:
        failures.append(
            f"exit mask: {seq} has {value}, expected {expected}"
        )

# return/cancel counts: single-return rows return 1/0, single-cancel 0/1,
# double-activate returns 2/0, mixed long rows 1/1.
return_cancel_expectations = {
    'f': ('0', '0'), 'fn': ('0', '0'), 'fnn': ('0', '0'), 'fnnn': ('0', '0'),
    'fa': ('0', '0'), 'fna': ('0', '0'), 'fnna': ('0', '0'),
    'faa': ('1', '0'), 'fnaa': ('1', '0'), 'fnnaa': ('1', '0'),
    'faaa': ('2', '0'), 'fnaaa': ('2', '0'), 'fnnaaa': ('2', '0'),
    'faaaa': ('3', '0'), 'fnaaaa': ('3', '0'), 'fnnaaaa': ('3', '0'),
    'faf': ('0', '0'), 'fnaf': ('0', '0'), 'fnnaf': ('0', '0'),
    'fai': ('0', '0'), 'fnai': ('0', '0'), 'fnnai': ('0', '0'),
    'fan': ('0', '1'), 'fnan': ('0', '1'), 'fnnan': ('0', '1'),
    'fann': ('0', '2'), 'fnann': ('0', '2'), 'fnnann': ('0', '2'),
    'fanan': ('1', '2'), 'fnanan': ('1', '2'), 'fnnanan': ('1', '2'),
    'faaf': ('1', '0'), 'fnaaf': ('1', '0'), 'fnnaaf': ('1', '0'),
    'faai': ('1', '0'), 'fnaai': ('1', '0'), 'fnnaai': ('1', '0'),
    'faan': ('1', '1'), 'fnaan': ('1', '1'), 'fnnaan': ('1', '1'),
    'faaifn': ('1', '1'), 'fnaaifn': ('1', '1'), 'fnnaaifn': ('1', '1'),
    'fab': ('1', '0'), 'fnab': ('1', '0'), 'fnnab': ('1', '0'),
    'fac': ('0', '1'), 'fnac': ('0', '1'), 'fnnac': ('0', '1'),
    'fabc': ('1', '1'), 'fnabc': ('1', '1'), 'fnnabc': ('1', '1'),
    'facb': ('1', '1'), 'fnacb': ('1', '1'), 'fnnacb': ('1', '1'),
}
for seq, (exp_r, exp_c) in return_cancel_expectations.items():
    row = get(seq)
    r_value = row['submenuReturnExitCount']
    c_value = row['submenuCancelExitCount']
    if r_value != exp_r:
        failures.append(
            f"return count: {seq} has {r_value}, expected {exp_r}"
        )
    if c_value != exp_c:
        failures.append(
            f"cancel count: {seq} has {c_value}, expected {exp_c}"
        )

# commit history invariants
# classes: 0=NONE, 1=SINGLE, 2=REPEATED_SAME, 3=REPEATED_VARIED
# masks: 1=COMMITTED, 2=REPEATED, 4=VARIED
# In the current architecture all activations in a run are from the same selection,
# so REPEATED_VARIED (3) never occurs. distinctCommittedSelections is always 0 or 1.
commit_history_expectations = {}
for seq in seqs:
    a_count = seq.count('a')
    if a_count == 0:
        commit_history_expectations[seq] = ('0', '0', '0')  # NONE, no mask, 0 distinct
    elif a_count == 1:
        commit_history_expectations[seq] = ('1', '1', '1')  # SINGLE, COMMITTED, 1 distinct
    else:
        commit_history_expectations[seq] = ('2', '3', '1')  # REPEATED_SAME, COMMITTED|REPEATED, 1 distinct
for seq, (exp_cls, exp_mask, exp_dist) in commit_history_expectations.items():
    row = get(seq)
    if row['commitHistoryClass'] != exp_cls:
        failures.append(
            f"commit history class: {seq} has {row['commitHistoryClass']}, expected {exp_cls}"
        )
    if row['commitHistoryMask'] != exp_mask:
        failures.append(
            f"commit history mask: {seq} has {row['commitHistoryMask']}, expected {exp_mask}"
        )
    if row['distinctCommittedSelections'] != exp_dist:
        failures.append(
            f"distinct committed selections: {seq} has {row['distinctCommittedSelections']}, expected {exp_dist}"
        )

# lane identity invariants
menu_expectations = {
    'f': ('0', '0', '0', '0'),
    'fn': ('1', '1', '0', '0'),
    'fnn': ('2', '2', '0', '0'),
    'fnnn': ('0', '0', '0', '0'),
}
for seq, expected in menu_expectations.items():
    row = get(seq)
    quad = (row['finalSelectionIndex'], row['selectedRenderVariant'], row['activatedGraphicIndex'], row['finalScreen'])
    if quad != expected:
        failures.append(
            f"menu identity: {seq} has {quad}, expected {expected}"
        )

lane_expectations = {
    'fa': ('0', '0', '11'),
    'fna': ('1', '1', '12'),
    'fnna': ('2', '2', '13'),
}

# new exit-centric rows must also keep lane identity
extra_lane_expectations = {
    'faaa': ('0', '0', '11'), 'fnaaa': ('1', '1', '12'), 'fnnaaa': ('2', '2', '13'),
    'faaaa': ('0', '0', '11'), 'fnaaaa': ('1', '1', '12'), 'fnnaaaa': ('2', '2', '13'),
    'fann': ('0', '0', '11'), 'fnann': ('1', '1', '12'), 'fnnann': ('2', '2', '13'),
    'fanan': ('0', '0', '11'), 'fnanan': ('1', '1', '12'), 'fnnanan': ('2', '2', '13'),
    'fab': ('0', '0', '11'), 'fnab': ('1', '1', '12'), 'fnnab': ('2', '2', '13'),
    'fac': ('0', '0', '11'), 'fnac': ('1', '1', '12'), 'fnnac': ('2', '2', '13'),
    'fabc': ('0', '0', '11'), 'fnabc': ('1', '1', '12'), 'fnnabc': ('2', '2', '13'),
    'facb': ('0', '0', '11'), 'fnacb': ('1', '1', '12'), 'fnnacb': ('2', '2', '13'),
}
for seq, expected in extra_lane_expectations.items():
    row = get(seq)
    triple = (row['finalSelectionIndex'], row['selectedRenderVariant'], row['activatedGraphicIndex'])
    if triple != expected:
        failures.append(
            f"extra lane identity: {seq} has {triple}, expected {expected}"
        )
for prefix, expected in lane_expectations.items():
    lane_rows = [row for row in rows if row['seq'].startswith(prefix)]
    for row in lane_rows:
        triple = (row['finalSelectionIndex'], row['selectedRenderVariant'], row['activatedGraphicIndex'])
        if triple != expected:
            failures.append(
                f"lane identity: {row['seq']} has {(triple)}, expected {expected}"
            )

inv = []
inv.append('# ReDMCSB M9 submenu matrix invariants\n')
inv.append('\n')
if failures:
    inv.append('Status: FAIL\n\n')
    for item in failures:
        inv.append(f'- {item}\n')
else:
    inv.append('Status: PASS\n\n')
    inv.append('- Pre-activation menu baseline matches the expected 0 -> 1 -> 2 -> 0 cycle\n')
    inv.append('- First activation pattern matches across lanes 11/12/13\n')
    inv.append('- Re-activate pattern matches across lanes 11/12/13\n')
    inv.append('- Frame-hold pattern matches across lanes 11/12/13\n')
    inv.append('- Idle-hold pattern matches across lanes 11/12/13\n')
    inv.append('- Suppressed-advance hold pattern matches across lanes 11/12/13\n')
    inv.append('- Mixed re-activate + hold patterns match across lanes 11/12/13\n')
    inv.append('- Explicit submenu behavior classes remain stable for the reported last-event class: none=0, reactivate=1, frame=2, idle=3, suppressed advance=4\n')
    inv.append('- Explicit cumulative submenu behavior classes remain stable for sequence semantics: mixed rows collapse to mixed=5 while single-mode rows stay none/reactivate/frame/idle/suppressed\n')
    inv.append('- Explicit submenu behavior masks remain stable as cumulative flags: reactivate=1, frame=2, idle=4, suppressed advance=8, combined long-row mix=15\n')
    inv.append('- Lane identity stays coupled: selection/render/graphic remain 0/0/11, 1/1/12, 2/2/13 for their respective lanes\n')
    inv.append('- Pre-activation menu identity stays coupled: f=0/0/0/0, fn=1/1/0/0, fnn=2/2/0/0, fnnn=0/0/0/0\n')
    inv.append('- Submenu exit classes remain stable: none=0, return=1, cancel=2, mixed=3; rows with only menu events or submenu holds stay NONE\n')
    inv.append('- Submenu exit masks remain stable as cumulative flags: return=1, cancel=2, combined=3\n')
    inv.append('- Single-activate rows (faa/fnaa/fnnaa, faaf/fnaaf/fnnaaf, faai/fnaai/fnnaai) report return=1 cancel=0\n')
    inv.append('- Single-cancel rows (fan/fnan/fnnan) report return=0 cancel=1\n')
    inv.append('- Mixed rows (faan/fnaan/fnnaan, faaifn/fnaaifn/fnnaaifn) report return=1 cancel=1\n')
    inv.append('- Deep-return rows faaa/faaaa and their fn/fnn siblings report return=2/3 cancel=0, exit class stays RETURN\n')
    inv.append('- Deep-cancel rows fann/fnann/fnnann report return=0 cancel=2, exit class stays CANCEL\n')
    inv.append('- Alternating rows fanan/fnanan/fnnanan report return=1 cancel=2, exit class collapses to MIXED=3\n')
    inv.append('- Game-state cumulative class stable: f=HELD, fn/fnn/fnnn=NAVIGATED, any row with an activate=ENTERED_SUBMENU\n')
    inv.append('- activationCommittedCount equals the number of `a` events in each sequence\n')
    inv.append('- enteredSubmenuCount equals 1 for every row with at least one `a`, and 0 otherwise (only `f` here)\n')
    inv.append('- Held-only row `f` keeps gameStateMask==HELD (16)\n')
    inv.append('- Commit history class stable: no-activation rows=NONE (0), single-activation rows=SINGLE (1), multi-activation rows=REPEATED_SAME (2)\n')
    inv.append('- Commit history mask stable: no-activation=0, single=COMMITTED (1), multi=COMMITTED|REPEATED (3)\n')
    inv.append('- All activations in current architecture originate from the same selection: distinctCommittedSelections is 0 or 1, REPEATED_VARIED never occurs\n')
    inv.append('- Explicit back event (b) produces behaviorClass=BACK (6), behaviorMask=16, return exit\n')
    inv.append('- Explicit cancel event (c) produces behaviorClass=CANCEL (7), behaviorMask=32, cancel exit\n')
    inv.append('- Combined back+cancel (bc/cb) produces mixed exit mask=3, cumulative behavior=MIXED (5), behavior mask=48\n')
    inv.append('- Back/cancel patterns match across lanes 11/12/13\n')

(out_dir / 'submenu_matrix.md').write_text(''.join(md), encoding='utf-8')
(out_dir / 'submenu_invariants.md').write_text(''.join(inv), encoding='utf-8')
print(out_dir / 'submenu_matrix.md')
print(out_dir / 'submenu_invariants.md')
if failures:
    raise SystemExit(1)
PY
