[sdl]
fullscreen=false
output=opengl

[dosbox]
machine=svga_paradise
memsize=4
captures=/home/trv2/work/firestaff/verification-m11/lane4-original-overlay-20260428-0917/prepare

[cpu]
core=normal
cputype=386
cpu_cycles=3000

[render]
aspect=false
integer_scaling=false

[mixer]
nosound=true

[speaker]
pcspeaker=false
tandy=off

[capture]
capture_dir=/home/trv2/work/firestaff/verification-m11/lane4-original-overlay-20260428-0917/prepare
default_image_capture_formats=raw

[autoexec]
mount c "/home/trv2/.openclaw/data/firestaff-original-games/DM/_extracted/dm-pc34/DungeonMasterPC34"
c:
DM VGA
