/* M11 source admission -> boot profile -> F0128/F0115 C14 blit. */
#include "m11_game_view.h"
#include <stdio.h>
#include <string.h>
typedef struct { int calls; } Probe;
static void put16(unsigned char *p,int o,unsigned short v){p[o]=(unsigned char)v;p[o+1]=(unsigned char)(v>>8);}
static int draw(void *u,const CSB_V1_ViewportRuntimeProjectileSpriteBlit *b,uint8_t *p,int s){Probe *q=u;if(!q||!b||!p||s<320||b->graphic_index!=487||!b->uses_f0791_blit||b->transparent_color!=10)return 0;++q->calls;p[33*s+112]=0x5a;return 1;}
static void fixture(CSB_V1_DungeonData *d,unsigned char r[224]){int i;memset(d,0,sizeof(*d));memset(r,0,224);d->level_count=2;d->level_widths[0]=d->level_widths[1]=2;d->level_heights[0]=d->level_heights[1]=2;d->level_offsets[1]=4;d->square_bytes=1;d->raw_data=r;d->raw_size=224;d->square_first_thing_base=96;d->square_first_thing_count=2;d->thing_data_bases[3]=160;d->thing_type_counts[3]=1;d->thing_data_bases[14]=184;d->thing_type_counts[14]=1;for(i=0;i<8;++i)r[i]=(unsigned char)(1u<<5);r[4]=(unsigned char)((1u<<5)|0x10u);put16(r,80,1);put16(r,98,(unsigned short)(3u<<10));put16(r,160,(unsigned short)(14u<<10));put16(r,184,0xfffeu);put16(r,186,0x1407u);r[188]=200;r[189]=45;put16(r,190,17);}
int main(void){M11_GameViewState m;CSB_V1_BootProfile b;CSB_V1_DungeonData d;CSB_V1_ViewportRuntimeDrawerBinding bind;CSB_V1_ViewportRuntimeDrawCounts counts;Probe probe;unsigned char raw[224];uint8_t frame[320*200];memset(&m,0,sizeof(m));memset(&b,0,sizeof(b));memset(&bind,0,sizeof(bind));memset(&counts,0,sizeof(counts));memset(&probe,0,sizeof(probe));memset(frame,0,sizeof(frame));fixture(&d,raw);b.runtime.dungeon_handle=&d;b.runtime.current_level=1;m.sourceKind=M11_GAME_SOURCE_CSB_BOOT;m.csbBootProfile=&b;if(!M11_GameView_AdmitCsbPostTeleportProjectileImpact(&m,1,0,0,(uint16_t)(14u<<10),CSB_V1_F0115_PROJECTILE_ORDINAL_M715,CSB_V1_F0115_PROJECTILE_SIDE_RIGHT,CSB_V1_F0115_PROJECTILE_COORDINATE_SET_MIDDLE)||b.post_teleport_projectile_handoff_count!=1u){fputs("M11 did not source-admit C14 into boot profile\n",stderr);return 1;}bind.projectile_sprite_drawer=draw;bind.projectile_sprite_user=&probe;if(!csb_v1_boot_render_viewport_frame_pc34(&b,frame,320,200,&bind,&counts)||probe.calls!=1||frame[33*320+112]!=0x5a||counts.post_teleport_projectile_handoff_drawn_count!=1||counts.projectile_marker_drawn_count!=0){fputs("M11 C14 boot route did not draw real F0115 material\n",stderr);return 1;}puts("ok: M11 C14 admission reaches boot F0128/F0115 without marker");return 0;}
