#include "nexus_v1_prs3_dgn_placement_adapter.h"
#include <stdio.h>
#include <string.h>
int main(void) { Nexus_V1_DgnActiveLevelRendererSourceReceipt d; Nexus_V1_Prs3Vdp1ConsumerEvidenceReceipt p; Nexus_V1_Prs3Vdp1CaptureReceipt c; Nexus_V1_Prs3DgnPlacementAdapterInput i; Nexus_V1_Prs3DgnPlacementAdapterReceipt r;
 memset(&d,0,sizeof(d)); memset(&p,0,sizeof(p)); memset(&c,0,sizeof(c)); memset(&i,0,sizeof(i)); d.valid=d.package_source_bound=d.vdp1_command_format_framed=d.vdp1_coordinate_words_framed=1; d.source_bytes_fnv1a64=7; d.vdp1_command_framing.command.xa=1; d.vdp1_command_framing.command.ya=2; p.trace_artifact_available=p.raw_trace_authenticated=p.trace_binds_dm_bin=p.trace_binds_menu_bpk_entry5=p.trace_binds_lev00_structure2=p.candidate_spans_bound=1; p.prs3_stream_offset=16; p.prs3_stream_size=12; p.prs3_header_span_fnv1a64=11; p.prs3_bitmap_candidate_fnv1a64=12; p.prs3_bitmap_candidate_offset=20; p.prs3_bitmap_candidate_size=8; p.palt_candidate_fnv1a64=13; p.palt_candidate_size=512; c.valid=c.complete_capture=c.dgn_placement_observed=1;c.schema_version=10;c.dgn_fnv1a64=7;c.dgn_descriptor_index=2;c.dgn_descriptor_fnv1a64=14;c.dgn_frame_sequence=10;c.dgn_command_sequence=c.vdp1_command_sequence=11;c.dgn_command_xa=1;c.dgn_command_ya=2; i.dgn=&d;i.prs3=&p;i.capture=&c;i.trace_fnv1a64=9;i.trace_size=1;i.traced_dgn_fnv1a64=7;i.descriptor_index=2;i.descriptor_fnv1a64=14;i.descriptor_envelope_valid=1;i.traced_xa=1;i.traced_ya=2;
 if(!nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)||!r.dgn_placement_observed||r.descriptor_index!=2||r.descriptor_fnv1a64!=14||r.frame_sequence!=10||r.command_sequence!=11||!r.no_draw_only||r.fallback_visuals_permitted||r.prs3_bitmap_candidate_fnv1a64!=12||r.prs3_bitmap_candidate_offset!=20||r.prs3_bitmap_candidate_size!=8||r.palt_candidate_fnv1a64!=13||r.palt_candidate_size!=512) return 1;
 c.dgn_descriptor_index=3; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; c.dgn_descriptor_index=2;c.dgn_command_xa=3; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1;c.dgn_command_xa=1;
 p.candidate_spans_bound=0; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; p.candidate_spans_bound=1; p.prs3_bitmap_candidate_size=7; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; p.prs3_bitmap_candidate_size=8;
 i.traced_dgn_fnv1a64=8; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; i.traced_dgn_fnv1a64=7;i.descriptor_fnv1a64=15; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; i.descriptor_fnv1a64=14;i.descriptor_envelope_valid=0; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; i.descriptor_envelope_valid=1;i.traced_xa=3; if(nexus_v1_prs3_dgn_placement_adapter_admit(&i,&r)) return 1; puts("prs3 dgn placement adapter: PASS"); return 0; }
