#include "csb_v1_f0646_f0665_text_bitmap_click_raw_pc34_compat.h"
#include <stdio.h>
#include <string.h>
static int failures,assertions;static void check(int c,const char *e,int l){++assertions;if(!c){++failures;fprintf(stderr,"FAIL:%d: %s\n",l,e);}}
#define CHECK(c) check((c),#c,__LINE__)
static CSB_V1_TextBitmapClickRawMaterialPc34 material(uint8_t*t,uint8_t*f,uint8_t*g,uint8_t*z,uint8_t*l,uint8_t*p,uint8_t*d,uint8_t*i,uint8_t*m){CSB_V1_TextBitmapClickRawMaterialPc34 r;memset(&r,0,sizeof(r));r.text_material=t;r.text_material_size=8;r.text_material_identity=0x64600001u;r.font_material=f;r.font_material_size=8;r.font_material_identity=0x64600002u;r.graphics_material=g;r.graphics_material_size=8;r.graphics_material_identity=0x64600003u;r.zone_material=z;r.zone_material_size=8;r.zone_material_identity=0x64600004u;r.timeline_material=l;r.timeline_material_size=8;r.timeline_material_identity=0x64600005u;r.palette_material=p;r.palette_material_size=8;r.palette_material_identity=0x64600006u;r.dungeon_material=d;r.dungeon_material_size=8;r.dungeon_material_identity=0x64600007u;r.input_material=i;r.input_material_size=8;r.input_material_identity=0x64600008u;r.memory_material=m;r.memory_material_size=8;r.memory_material_identity=0x64600009u;r.authenticated_pc34=1;return r;}
static void test_receipt_never_blits_or_clicks(void){uint8_t t[8]={1},f[8]={2},g[8]={3},z[8]={4},l[8]={5},p[8]={6},d[8]={7},i[8]={8},m[8]={9},before[8];CSB_V1_TextBitmapClickRawMaterialPc34 raw=material(t,f,g,z,l,p,d,i,m);CSB_V1_TextBitmapClickAuditReceiptPc34 receipt;memcpy(before,g,sizeof(g));CHECK(csb_v1_f0646_f0665_text_bitmap_click_audit_pc34(&raw,CSB_V1_TEXT_BITMAP_CLICK_F0664,&receipt)==1);CHECK(receipt.dungeon_material_required&&receipt.input_material_required&&receipt.runtime_execution_blocked);CHECK(memcmp(before,g,sizeof(g))==0);raw.dungeon_material_identity=0;CHECK(csb_v1_f0646_f0665_text_bitmap_click_audit_pc34(&raw,CSB_V1_TEXT_BITMAP_CLICK_F0664,&receipt)==0);}
static void test_all_symbols(void){uint8_t t[8]={1},f[8]={2},g[8]={3},z[8]={4},l[8]={5},p[8]={6},d[8]={7},i[8]={8},m[8]={9};CSB_V1_TextBitmapClickRawMaterialPc34 raw=material(t,f,g,z,l,p,d,i,m);CSB_V1_TextBitmapClickAuditReceiptPc34 receipt;int id;for(id=CSB_V1_TEXT_BITMAP_CLICK_F0646;id<=CSB_V1_TEXT_BITMAP_CLICK_F0665;++id){CHECK(csb_v1_f0646_f0665_text_bitmap_click_audit_pc34(&raw,(CSB_V1_TextBitmapClickFunctionPc34)id,&receipt)==1);CHECK(receipt.function_id==(CSB_V1_TextBitmapClickFunctionPc34)id&&receipt.source_evidence!=NULL);CHECK(receipt.raw_material_admitted&&receipt.runtime_execution_blocked);}CHECK(csb_v1_f0646_f0665_text_bitmap_click_audit_pc34(&raw,(CSB_V1_TextBitmapClickFunctionPc34)645,&receipt)==0);}
int main(void){test_receipt_never_blits_or_clicks();test_all_symbols();printf("csb_v1_f0646_f0665_text_bitmap_click_raw: %d/%d assertions passed\n",assertions-failures,assertions);return failures?1:0;}
