/*
 * test_dm1_v1_hidpi_chest_slot_hit_zone_pc34_compat.c
 *
 * DM1 V1 high-DPI / window-scale mouse-mapping regression for one
 * inventory/chest hit zone. Verifies that scaled window coordinates
 * route to the same chest slot box as the source-locked 320x200
 * coordinates for the touch-matrix panel dispatch path and the SDL
 * render framebuffer-map path.
 *
 * ReDMCSB source lock:
 *   - COMMAND.C:215-227 G0456_as_Graphic561_MouseInput_PanelChest[8] =
 *     { { C058..C065, Box.Left, Box.Right, Box.Top, Box.Bottom, Button } }
 *     chest_1..chest_8 zones are C537..C544 with viewport-relative
 *     Box.Left / Box.Top per the panel layout-696 C106 child zones.
 *   - COMMAND.C:498-506 inventory.chest_1..chest_8 zone table
 *     (C058..C065 -> C537..C544).
 *   - COMMAND.C:1982 F0378 M569_PANEL_CHEST dispatch.
 *   - CHAMPION.C:662-712 F0302 chest slot routing via
 *     G0425_aT_ChestSlots.
 *   - CHEST.C:30-76 F0333 open chest panel + slot population.
 *   - COORD.C viewport origin/extent (x=0 y=33 w=224 h=136).
 *   - COMMAND.C:1641-1644 source-orders primary mouse input before
 *     secondary mouse input, and the chest-panel subtable is only
 *     scanned after the primary / secondary movement tables miss.
 *     That ordering is exactly what
 *     TOUCHCLICK_Compat_MapScaledViewportPointToDispatch exercises
 *     via MapViewportLocalPointToDispatch ->
 *     HitTestInCoordMode(VIEWPORT_RELATIVE) (the panel path).
 *
 * Test scope (narrow regression):
 *   - MapScaledViewportPointToDispatch routes chest_1 (C537) and
 *     chest_8 (C544) box hits on multiple surface sizes (1280x720,
 *     1920x1080, 2560x1440, plus 1512x982 MacBook Pro Retina as the
 *     original HiDPI failure case). The viewport-letterbox math
 *     uses (224, 136), not (320, 200), so the surface pixel that
 *     lands on chest_1 via the viewport path is NOT the same as
 *     the one that lands on chest_1 via the screen path.
 *   - MapScaledScreenPointToDispatch routes the same chest_1 click
 *     into viewport.dungeon (C080) — the source-ordered primary
 *     table scans screen-relative zones first and the chest slots
 *     are panel-table zones. Lock that this is what happens; a
 *     future regression that lets a chest slot leak into the
 *     primary table scan would be caught.
 *   - The SDL render framebuffer map
 *     (M11_Render_MapPointToFramebuffer) lands inside the source
 *     320x200 chest_1 / chest_8 box from a scaled logical window
 *     click.
 *   - Off-by-one neighbor clicks do not regress into a wrong chest
 *     slot zone (one physical pixel off the chest_1 box still
 *     misses C537/C538/C544 — it may land on a panel zone such as
 *     panel.resurrect, which is correct source-locked behavior).
 *
 * Chest slot source coordinates (COMMAND.C:215-227):
 *   chest_1: viewport (117, 59, 16, 16) -> screen (117, 92, 16, 16)
 *   chest_8: viewport (196, 105, 16, 16) -> screen (196, 138, 16, 16)
 *
 * For each surface, the pre-computed physical click points below
 * map back to source coordinates inside the chest_1 box on the
 * 320x200 grid (and inside the chest_1 box on the 224x136
 * viewport grid, respectively). Each test point was generated by
 * searching the integer letterbox math for the first physical
 * pixel whose inverse normalize lands on the chest_1 box origin
 * or center; the same math is what
 * TOUCHCLICK_Compat_NormalizeLetterboxedPointPc34Compat and
 * M11_Render_MapPointToFramebuffer compute.
 */

#include "render_sdl_m11.h"
#include "touch_click_zone_matrix_pc34_compat.h"

#include <stdio.h>
#include <string.h>

static int g_failures = 0;
static int g_pass = 0;

#define CHECK(expr) do { \
    if (!(expr)) { \
        fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #expr); \
        ++g_failures; \
    } else { \
        ++g_pass; \
    } \
} while (0)

static int dispatch_scaled_viewport(int physicalX,
                                    int physicalY,
                                    int surfaceW,
                                    int surfaceH,
                                    TouchClickDispatchPc34Compat* outDispatch) {
    return TOUCHCLICK_Compat_MapScaledViewportPointToDispatch(physicalX,
                                                              physicalY,
                                                              surfaceW,
                                                              surfaceH,
                                                              TOUCH_CLICK_BUTTON_LEFT_PC34_COMPAT,
                                                              outDispatch);
}

static int dispatch_scaled_screen(int physicalX,
                                  int physicalY,
                                  int surfaceW,
                                  int surfaceH,
                                  TouchClickDispatchPc34Compat* outDispatch) {
    return TOUCHCLICK_Compat_MapScaledScreenPointToDispatch(physicalX,
                                                            physicalY,
                                                            surfaceW,
                                                            surfaceH,
                                                            TOUCH_CLICK_BUTTON_LEFT_PC34_COMPAT,
                                                            outDispatch);
}

/*
 * chest_1 box source-locked: COMMAND.C:215-227 Box.Left=117 Box.Top=92,
 * C058 -> C537 inventory chest 1, viewport-relative Box (117, 59, 16, 16).
 * Pre-computed physical pixels per surface (viewport-letterbox 224x136):
 *
 *   surface       | chest_1 center (125,67)
 *   --------------|-----------------------------
 *   1280 x 720    |   (709, 355)
 *   1920 x 1080   |   (1064, 533)
 *   2560 x 1440   |   (1418, 710)
 *   1512 x 982    |   (844, 485)
 */
static void expect_chest_1_viewport_dispatch(int surfaceW,
                                             int surfaceH,
                                             int physicalX,
                                             int physicalY) {
    TouchClickDispatchPc34Compat dispatch;
    CHECK(dispatch_scaled_viewport(physicalX, physicalY,
                                   surfaceW, surfaceH, &dispatch) == 1);
    CHECK(dispatch.commandId == 58u);
    CHECK(dispatch.zoneIndex == 537u);
    CHECK(dispatch.coordMode == TOUCH_CLICK_COORD_VIEWPORT_RELATIVE_PC34_COMPAT);
    CHECK(strcmp(dispatch.groupName, "inventory.chest_1") == 0);
    /* MapScaledViewportPointToDispatch promotes viewport-local to
     * screen-local by adding sourceViewportY=33. The dispatched
     * screenX/screenY is therefore the screen-local point inside
     * the chest_1 box [117..132, 92..107]. */
    CHECK(dispatch.screenX >= 117 && dispatch.screenX <= 132);
    CHECK(dispatch.screenY >= 92 && dispatch.screenY <= 107);
}

/*
 * chest_8 box source-locked: COMMAND.C:215-227 Box.Left=196 Box.Top=138,
 * C065 -> C544 inventory chest 8, viewport-relative Box (196, 105, 16, 16).
 * Pre-computed physical pixels per surface (viewport-letterbox 224x136):
 *
 *   surface       | chest_8 center (204,113)
 *   --------------|-----------------------------
 *   1280 x 720    |   (1127, 599)
 *   1920 x 1080   |   (1691, 898)
 *   2560 x 1440   |   (2254, 1197)
 *   1512 x 982    |   (1377, 795)
 */
static void expect_chest_8_viewport_dispatch(int surfaceW,
                                             int surfaceH,
                                             int physicalX,
                                             int physicalY) {
    TouchClickDispatchPc34Compat dispatch;
    CHECK(dispatch_scaled_viewport(physicalX, physicalY,
                                   surfaceW, surfaceH, &dispatch) == 1);
    CHECK(dispatch.commandId == 65u);
    CHECK(dispatch.zoneIndex == 544u);
    CHECK(dispatch.coordMode == TOUCH_CLICK_COORD_VIEWPORT_RELATIVE_PC34_COMPAT);
    CHECK(strcmp(dispatch.groupName, "inventory.chest_8") == 0);
    CHECK(dispatch.screenX >= 196 && dispatch.screenX <= 211);
    CHECK(dispatch.screenY >= 138 && dispatch.screenY <= 153);
}

/*
 * The screen dispatch path (primary / secondary source-ordered scan)
 * only scans screen-relative zones, so the same physical click that
 * hits chest_1 via the viewport panel path routes to viewport.dungeon
 * (C080) here. This is the source-locked COMMAND.C:1641-1644 ordering:
 * a regression that lets chest slots leak into the screen-relative
 * primary scan would be visible here.
 *
 * Pre-computed physical pixels per surface (screen-letterbox 320x200):
 *
 *   surface       | chest_1 center (125,100)
 *   --------------|-----------------------------
 *   1280 x 720    |   (514, 360)
 *   1920 x 1080   |   (771, 540)
 *   2560 x 1440   |   (1028, 720)
 *   1512 x 982    |   (591, 491)
 */
static void expect_chest_1_screen_path_routes_to_viewport(int surfaceW,
                                                           int surfaceH,
                                                           int physicalX,
                                                           int physicalY) {
    TouchClickDispatchPc34Compat dispatch;
    CHECK(dispatch_scaled_screen(physicalX, physicalY,
                                 surfaceW, surfaceH, &dispatch) == 1);
    CHECK(dispatch.commandId == 80u);
    CHECK(dispatch.zoneIndex == 7u);
    CHECK(strcmp(dispatch.groupName, "viewport.dungeon") == 0);
    CHECK(dispatch.coordMode == TOUCH_CLICK_COORD_SCREEN_RELATIVE_PC34_COMPAT);
    /* The screen dispatch records the normalized source point; for
     * chest_1 it must land inside the chest_1 box [117..132, 92..107]. */
    CHECK(dispatch.screenX >= 117 && dispatch.screenX <= 132);
    CHECK(dispatch.screenY >= 92 && dispatch.screenY <= 107);
}

/*
 * Verify M11_Render_MapPointToFramebuffer (SDL render framebuffer map)
 * lands inside the source chest_1 / chest_8 box. Uses screen-letterbox
 * 320x200 (the M11 default content).
 */
static void expect_chest_1_fb_in_box(int surfaceW,
                                     int surfaceH,
                                     int logicalX,
                                     int logicalY) {
    int fbX = -1;
    int fbY = -1;
    int rc = M11_Render_MapPointToFramebuffer(logicalX,
                                              logicalY,
                                              surfaceW,
                                              surfaceH,
                                              M11_FB_WIDTH,
                                              M11_FB_HEIGHT,
                                              M11_SCALE_FIT,
                                              0,
                                              M11_DISPLAY_ASPECT_CONTENT,
                                              &fbX,
                                              &fbY);
    CHECK(rc == 1);
    CHECK(fbX >= 117 && fbX <= 132);
    CHECK(fbY >= 92 && fbY <= 107);
}

static void expect_chest_8_fb_in_box(int surfaceW,
                                     int surfaceH,
                                     int logicalX,
                                     int logicalY) {
    int fbX = -1;
    int fbY = -1;
    int rc = M11_Render_MapPointToFramebuffer(logicalX,
                                              logicalY,
                                              surfaceW,
                                              surfaceH,
                                              M11_FB_WIDTH,
                                              M11_FB_HEIGHT,
                                              M11_SCALE_FIT,
                                              0,
                                              M11_DISPLAY_ASPECT_CONTENT,
                                              &fbX,
                                              &fbY);
    CHECK(rc == 1);
    CHECK(fbX >= 196 && fbX <= 211);
    CHECK(fbY >= 138 && fbY <= 153);
}

/*
 * Off-by-one neighbor regression: a click just outside the chest_1
 * box on the viewport path must NOT resolve to chest_1 / chest_2 /
 * chest_8. We accept any other dispatch (e.g. panel.resurrect or
 * panel.reincarnate) or no dispatch at all (return 0). The original
 * fail-mode was "wrong chest slot for clicks outside the box".
 */
static void expect_neighbor_misses_chest_slots(int surfaceW,
                                               int surfaceH,
                                               int physicalX,
                                               int physicalY) {
    TouchClickDispatchPc34Compat dispatch;
    if (dispatch_scaled_viewport(physicalX, physicalY,
                                 surfaceW, surfaceH, &dispatch) == 1) {
        CHECK(dispatch.zoneIndex != 537u);
        CHECK(dispatch.zoneIndex != 538u);
        CHECK(dispatch.zoneIndex != 544u);
    }
}

int main(void) {
    printf("probe=firestaff_dm1_v1_hidpi_chest_slot_hit_zone_pc34_compat\n");
    printf("sourceEvidence=%s\n", TOUCHCLICK_Compat_GetSourceEvidence());
    printf("sourceChestSlots=%s\n",
           "COMMAND.C:215-227 G0456_as_Graphic561_MouseInput_PanelChest[8]; "
           "COMMAND.C:498-506 inventory.chest_1..chest_8; "
           "COMMAND.C:1982 F0378 M569_PANEL_CHEST; "
           "COMMAND.C:1641-1644 primary before secondary source ordering; "
           "CHAMPION.C:662-712 F0302 chest slot routing; "
           "CHEST.C:30-76 F0333 open chest + slot population");

    /*
     * Chest_1 box source: screen (117, 92, 16, 16), center (125, 100).
     * Chest_8 box source: screen (196, 138, 16, 16), center (204, 145).
     *
     * Pre-computed physical pixels per surface:
     *
     *   surface       | vp (chest_1) | vp (chest_8) | screen (chest_1)
     *   --------------|--------------|--------------|-------------------
     *   1280 x 720    | (709, 355)   | (1127, 599)  | (514, 360)
     *   1920 x 1080   | (1064, 533)  | (1691, 898)  | (771, 540)
     *   2560 x 1440   | (1418, 710)  | (2254, 1197) | (1028, 720)
     *   1512 x 982    | (844, 485)   | (1377, 795)  | (591, 491)
     *
     * The "vp" column maps via the viewport-letterbox (224x136)
     * used by MapScaledViewportPointToDispatch. The "screen" column
     * maps via the screen-letterbox (320x200) used by
     * MapScaledScreenPointToDispatch and M11_Render_MapPointToFramebuffer.
     * The two letterboxes use different drawW/drawH/drawX/drawY, so
     * the surface pixel for the same source point differs.
     */

    /* 1280x720 (16:9 letterbox; vp drawW=1185 drawH=720 drawX=47 drawY=0,
     * screen drawW=1152 drawH=720 drawX=64 drawY=0). */
    expect_chest_1_viewport_dispatch(1280, 720, /*phys*/ 709, /*phys*/ 355);
    expect_chest_1_screen_path_routes_to_viewport(1280, 720, 514, 360);
    expect_chest_1_fb_in_box(1280, 720, /*logical*/ 514, /*logical*/ 360);

    /* 1920x1080 (1.78:1, no letterbox bars on either path). */
    expect_chest_1_viewport_dispatch(1920, 1080, 1064, 533);
    expect_chest_1_screen_path_routes_to_viewport(1920, 1080, 771, 540);
    expect_chest_1_fb_in_box(1920, 1080, 771, 540);

    /* 2560x1440 (4K HiDPI letterbox; vp drawW=1856 drawH=1125 drawX=176 drawY=157,
     * screen drawW=2304 drawH=1440 drawX=128 drawY=0). */
    expect_chest_1_viewport_dispatch(2560, 1440, 1418, 710);
    expect_chest_1_screen_path_routes_to_viewport(2560, 1440, 1028, 720);
    expect_chest_1_fb_in_box(2560, 1440, 1028, 720);

    /* 1512x982 MacBook Pro Retina (16" pre-2024). The failure case
     * in check_macbook_retina_drawable_rect_regression in
     * test_m11_display_aspect_present_rect.c. */
    expect_chest_1_viewport_dispatch(1512, 982, 844, 485);
    expect_chest_1_screen_path_routes_to_viewport(1512, 982, 591, 491);
    expect_chest_1_fb_in_box(1512, 982, 591, 491);

    /* Spot-check chest_8 on two distinct surfaces. */
    expect_chest_8_viewport_dispatch(1280, 720, 1127, 599);
    expect_chest_8_fb_in_box(1280, 720, 770, 497);

    expect_chest_8_viewport_dispatch(1512, 982, 1377, 795);
    expect_chest_8_fb_in_box(1512, 982, 927, 671);

    /*
     * Off-by-one regression: a click just left of chest_1 (one
     * viewport-letterbox physical pixel less than the in-box
     * chest_1 sample) on a 1280x720 surface must not resolve to
     * chest_1 / chest_2 / chest_8 via the viewport dispatch path.
     * We accept any other dispatch (e.g. panel.resurrect at source
     * (116, 92)) or no dispatch at all (return 0). The original
     * fail-mode was "wrong chest slot for clicks outside the box".
     */
    expect_neighbor_misses_chest_slots(1280, 720, /*phys*/ 665, /*phys*/ 313);

    /*
     * Source lock: the source viewport rect must remain
     * (0, 33, 224, 136) per COORD.C. The HiDPI scaling must not
     * bleed into the source view.
     */
    {
        int vx = -1, vy = -1, vw = -1, vh = -1;
        CHECK(TOUCHCLICK_Compat_GetSourceViewportRect(&vx, &vy, &vw, &vh) == 1);
        CHECK(vx == 0);
        CHECK(vy == 33);
        CHECK(vw == 224);
        CHECK(vh == 136);
    }

    printf("result=%s\n", g_failures == 0 ? "PASS" : "FAIL");
    printf("summary=pass=%d fail=%d\n", g_pass, g_failures);

    return g_failures == 0 ? 0 : 1;
}
