#include "csb_v1_f0621_f0645_champion_layout_text_raw_pc34_compat.h"
#include <stdio.h>
#include <string.h>
static int failures,assertions;static void check(int c,const char *e,int l){++assertions;if(!c){++failures;fprintf(stderr,"FAIL:%d: %s\n",l,e);}}
#define CHECK(c) check((c),#c,__LINE__)
static CSB_V1_ChampionLayoutTextRawMaterialPc34 material(uint8_t *c,uint8_t *z,uint8_t *g,uint8_t *f,uint8_t *t,uint8_t *i,uint8_t *m){CSB_V1_ChampionLayoutTextRawMaterialPc34 r;memset(&r,0,sizeof(r));
r.champion_material=c;r.champion_material_size=8;r.champion_material_identity=0x62100001u;r.zone_layout_material=z;r.zone_layout_material_size=8;r.zone_layout_material_identity=0x62100002u;r.graphics_material=g;r.graphics_material_size=8;r.graphics_material_identity=0x62100003u;r.font_material=f;r.font_material_size=8;r.font_material_identity=0x62100004u;r.text_material=t;r.text_material_size=8;r.text_material_identity=0x62100005u;r.input_material=i;r.input_material_size=8;r.input_material_identity=0x62100006u;r.memory_material=m;r.memory_material_size=8;r.memory_material_identity=0x62100007u;r.authenticated_pc34=1;return r;}
static void test_text_receipt_never_prints(void){uint8_t c[8]={1},z[8]={2},g[8]={3},f[8]={4},t[8]={5},i[8]={6},m[8]={7},before[8];CSB_V1_ChampionLayoutTextRawMaterialPc34 raw=material(c,z,g,f,t,i,m);CSB_V1_ChampionLayoutTextAuditReceiptPc34 receipt;memcpy(before,t,sizeof(t));CHECK(csb_v1_f0621_f0645_champion_layout_text_audit_pc34(&raw,CSB_V1_CHAMPION_LAYOUT_TEXT_F0644,&receipt)==1);CHECK(receipt.font_material_required&&receipt.text_material_required&&receipt.runtime_execution_blocked);CHECK(memcmp(before,t,sizeof(t))==0);raw.font_material_identity=0;CHECK(csb_v1_f0621_f0645_champion_layout_text_audit_pc34(&raw,CSB_V1_CHAMPION_LAYOUT_TEXT_F0644,&receipt)==0);}
static void test_all_bound_symbols_and_holes(void){uint8_t c[8]={1},z[8]={2},g[8]={3},f[8]={4},t[8]={5},i[8]={6},m[8]={7};CSB_V1_ChampionLayoutTextRawMaterialPc34 raw=material(c,z,g,f,t,i,m);CSB_V1_ChampionLayoutTextAuditReceiptPc34 receipt;int id;for(id=CSB_V1_CHAMPION_LAYOUT_TEXT_F0621;id<=CSB_V1_CHAMPION_LAYOUT_TEXT_F0645;++id){if(id==624||id==634||id==639||id==640)continue;CHECK(csb_v1_f0621_f0645_champion_layout_text_audit_pc34(&raw,(CSB_V1_ChampionLayoutTextFunctionPc34)id,&receipt)==1);CHECK(receipt.function_id==(CSB_V1_ChampionLayoutTextFunctionPc34)id&&receipt.source_evidence!=NULL);CHECK(receipt.raw_material_admitted&&receipt.runtime_execution_blocked);}CHECK(csb_v1_f0621_f0645_champion_layout_text_audit_pc34(&raw,CSB_V1_CHAMPION_LAYOUT_TEXT_F0624,&receipt)==0);CHECK(csb_v1_f0621_f0645_champion_layout_text_audit_pc34(&raw,CSB_V1_CHAMPION_LAYOUT_TEXT_F0634,&receipt)==0);}
int main(void){test_text_receipt_never_prints();test_all_bound_symbols_and_holes();printf("csb_v1_f0621_f0645_champion_layout_text_raw: %d/%d assertions passed\n",assertions-failures,assertions);return failures?1:0;}
