[sdl]
fullscreen=false
output=opengl

[dosbox]
machine=svga_paradise
memsize=4
captures=/Users/bosse/.openclaw/workspace-main/verification-screens/pass1052-dm1-original-route-24h-turncycle

[cpu]
core=normal
cputype=386
cpu_cycles=3000

[render]
aspect=false
integer_scaling=false

[mixer]
nosound=true

[speaker]
pcspeaker=false
tandy=off

[capture]
capture_dir=/Users/bosse/.openclaw/workspace-main/verification-screens/pass1052-dm1-original-route-24h-turncycle
default_image_capture_formats=raw

[autoexec]
mount c "/Users/bosse/.openclaw/data/firestaff-original-games/DM/_extracted/dm-pc34/DungeonMasterPC34"
c:
DM -vv -sn -pk
