#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "dm1_v1_collision_door_pc34_compat.h"
#include "dm1_v1_viewport_fakewall_pc34_compat.h"
#include "memory_dungeon_dat_pc34_compat.h"
#include "memory_movement_pc34_compat.h"

#define DM1_CANONICAL_DUNGEON_SHA256 "d90b6b1c38fd17e41d63682f8afe5ca3341565b5f5ddae5545f0ce78754bdd85"

struct CaseRef { int found; int mapIndex; int x; int y; unsigned char square; int doorIndex; };
static const char* default_dm1_dungeon_dat(void) { static char path[1024]; const char* home = getenv("HOME"); if (!home || home[0] == 0) home = "/home/trv2"; snprintf(path, sizeof(path), "%s/.openclaw/data/firestaff-original-games/DM/_canonical/dm1/DUNGEON.DAT", home); return path; }
static int expect_int(const char* label, int got, int want) { if (got != want) { fprintf(stderr, "FAIL %s got=%d want=%d\n", label, got, want); return 0; } return 1; }
static int expect_true(const char* label, int value) { return expect_int(label, value ? 1 : 0, 1); }
static int tile_index(const struct DungeonDatState_Compat* dungeon, int mapIndex, int x, int y) { return x * (int)dungeon->maps[mapIndex].height + y; }
static unsigned char read_square(const struct DungeonDatState_Compat* dungeon, int mapIndex, int x, int y) { return dungeon->tiles[mapIndex].squareData[tile_index(dungeon, mapIndex, x, y)]; }
static int square_first_thing_index(const struct DungeonDatState_Compat* dungeon, int mapIndex, int x, int y) { int total = 0; const struct DungeonMapDesc_Compat* map; int squareIndex; if (!dungeon || mapIndex < 0 || mapIndex >= (int)dungeon->header.mapCount) return -1; map = &dungeon->maps[mapIndex]; if (x < 0 || x >= (int)map->width || y < 0 || y >= (int)map->height) return -1; squareIndex = tile_index(dungeon, mapIndex, x, y); if (!(dungeon->tiles[mapIndex].squareData[squareIndex] & DUNGEON_SQUARE_MASK_THING_LIST)) return -1; for (int m = 0; m < mapIndex; ++m) { int count = (int)dungeon->maps[m].width * (int)dungeon->maps[m].height; for (int i = 0; i < count; ++i) if (dungeon->tiles[m].squareData[i] & DUNGEON_SQUARE_MASK_THING_LIST) ++total; } for (int i = 0; i <= squareIndex; ++i) if (dungeon->tiles[mapIndex].squareData[i] & DUNGEON_SQUARE_MASK_THING_LIST) ++total; return total - 1; }
static int first_door_index_on_square(const struct DungeonDatState_Compat* dungeon, const struct DungeonThings_Compat* things, int mapIndex, int x, int y) { int sftIndex = square_first_thing_index(dungeon, mapIndex, x, y); unsigned short thing; int type, index; if (!things || !things->loaded || !things->squareFirstThings || sftIndex < 0 || sftIndex >= things->squareFirstThingCount) return -1; thing = things->squareFirstThings[sftIndex]; if (thing == THING_NONE || thing == THING_ENDOFLIST) return -1; type = THING_GET_TYPE(thing); index = THING_GET_INDEX(thing); if (type != THING_TYPE_DOOR || index < 0 || index >= things->doorCount) return -1; return index; }
static int place_party_adjacent_to(const struct DungeonDatState_Compat* dungeon, int mapIndex, int x, int y, struct PartyState_Compat* party) { static const int px[4] = { 0, -1, 0, 1 }; static const int py[4] = { 1, 0, -1, 0 }; static const int dir[4] = { 0, 1, 2, 3 }; memset(party, 0, sizeof(*party)); for (int i = 0; i < 4; ++i) { int sx = x + px[i], sy = y + py[i]; if (F0706_MOVEMENT_IsSquarePassable_Compat(dungeon, mapIndex, sx, sy)) { party->mapIndex = mapIndex; party->mapX = sx; party->mapY = sy; party->direction = dir[i]; party->championCount = 1; return 1; } } return 0; }
static void set_case(struct CaseRef* ref, int mapIndex, int x, int y, unsigned char square, int doorIndex) { ref->found = 1; ref->mapIndex = mapIndex; ref->x = x; ref->y = y; ref->square = square; ref->doorIndex = doorIndex; }
static void print_case(const char* label, const struct CaseRef* ref, int passable, int collisionCode, int overlayOpen) { printf("case=%s map=%d x=%d y=%d raw=0x%02x passable=%d collisionCode=%d overlayOpen=%d doorIndex=%d\n", label, ref->mapIndex, ref->x, ref->y, ref->square, passable, collisionCode, overlayOpen, ref->doorIndex); }

int main(int argc, char** argv) {
    const char* dungeonPath = argc > 1 ? argv[1] : getenv("FIRESTAFF_DM1_CANONICAL_DUNGEON_DAT");
    struct DungeonDatState_Compat dungeon; struct DungeonThings_Compat things;
    struct CaseRef wall = {0,0,0,0,0,-1}, closedDoor = {0,0,0,0,0,-1}, buttonDoor = {0,0,0,0,0,-1}, openFakewall = {0,0,0,0,0,-1}, closedFakewall = {0,0,0,0,0,-1};
    struct Dm1V1CollisionResult collision; struct Dm1V1DoorInteractionResult click; struct PartyState_Compat party;
    unsigned char savedDoorSquare; int doorThingButtonCount = 0, doorSquareCount = 0, fakewallCount = 0, wallCount = 0, ok = 1;
    if (!dungeonPath || dungeonPath[0] == 0) dungeonPath = default_dm1_dungeon_dat();
    printf("probe=firestaff_dm1_v1_original_collision_overlay_runtime_probe\n"); printf("dungeon=%s\n", dungeonPath); printf("dungeon_sha256=%s\n", DM1_CANONICAL_DUNGEON_SHA256); printf("source=ReDMCSB_WIP20210206/Toolchains/Common/Source CLIKMENU.C:F0366:264-328 DUNGEON.C:F0172:2522-2706 CLIKVIEW.C:F0377:352-385 TIMELINE.C:F0241/F0244:711-910\n");
    memset(&dungeon, 0, sizeof(dungeon)); memset(&things, 0, sizeof(things));
    if (!F0500_DUNGEON_LoadDatHeader_Compat(dungeonPath, &dungeon) || !F0502_DUNGEON_LoadTileData_Compat(dungeonPath, &dungeon) || !F0504_DUNGEON_LoadThingData_Compat(dungeonPath, &dungeon, &things)) { fprintf(stderr, "FAIL load canonical dungeon path=%s\n", dungeonPath); return 1; }
    for (int mapIndex = 0; mapIndex < (int)dungeon.header.mapCount; ++mapIndex) { const struct DungeonMapDesc_Compat* map = &dungeon.maps[mapIndex]; for (int x = 0; x < (int)map->width; ++x) for (int y = 0; y < (int)map->height; ++y) { unsigned char square = read_square(&dungeon, mapIndex, x, y); int element = (square & DUNGEON_SQUARE_MASK_TYPE) >> 5; if (element == DUNGEON_ELEMENT_WALL) { ++wallCount; if (!wall.found) set_case(&wall, mapIndex, x, y, square, -1); } else if (element == DUNGEON_ELEMENT_DOOR) { int doorIndex = first_door_index_on_square(&dungeon, &things, mapIndex, x, y); ++doorSquareCount; if (!closedDoor.found && (square & 0x07) >= 2 && (square & 0x07) <= 4) set_case(&closedDoor, mapIndex, x, y, square, doorIndex); if (doorIndex >= 0 && things.doors[doorIndex].button) { ++doorThingButtonCount; if (!buttonDoor.found && place_party_adjacent_to(&dungeon, mapIndex, x, y, &party)) set_case(&buttonDoor, mapIndex, x, y, square, doorIndex); } } else if (element == DUNGEON_ELEMENT_FAKEWALL) { ++fakewallCount; if ((square & 0x04) && !openFakewall.found) set_case(&openFakewall, mapIndex, x, y, square, -1); if (!(square & 0x04) && !closedFakewall.found) set_case(&closedFakewall, mapIndex, x, y, square, -1); } } }
    printf("counts walls=%d doors=%d buttonDoors=%d fakewalls=%d\n", wallCount, doorSquareCount, doorThingButtonCount, fakewallCount);
    ok &= expect_true("canonical wall case", wall.found); ok &= expect_true("canonical closed door case", closedDoor.found); ok &= expect_true("canonical button door case", buttonDoor.found); ok &= expect_true("canonical fakewall case", openFakewall.found || closedFakewall.found);
    if (wall.found) { (void)DM1_V1_Collision_QuerySquare(&dungeon, wall.mapIndex, wall.x, wall.y, &collision); print_case("wall", &wall, F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, wall.mapIndex, wall.x, wall.y), collision.code, M11_DM1_ViewportSquareIsOpenPc34(wall.square)); ok &= expect_int("wall collision blocks", collision.code, DM1_COLLISION_BLOCKED_WALL); ok &= expect_int("wall movement passability", F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, wall.mapIndex, wall.x, wall.y), 0); ok &= expect_int("wall overlay wall-like", M11_DM1_ViewportSquareIsWallLikePc34(wall.square), 1); }
    if (closedDoor.found) { (void)DM1_V1_Collision_QuerySquare(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y, &collision); print_case("closed_door", &closedDoor, F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y), collision.code, M11_DM1_ViewportSquareIsOpenPc34(closedDoor.square)); ok &= expect_int("closed door collision blocks", collision.code, DM1_COLLISION_BLOCKED_DOOR); ok &= expect_int("closed door movement passability", F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y), 0); ok &= expect_int("closed door overlay closed", M11_DM1_ViewportSquareIsOpenPc34(closedDoor.square), 0); savedDoorSquare = read_square(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y); ok &= expect_int("open door runtime mutation", DM1_V1_Door_ApplyToggle(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y, DM1_DOOR_STATE_OPEN), 1); closedDoor.square = read_square(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y); (void)DM1_V1_Collision_QuerySquare(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y, &collision); print_case("open_door_runtime", &closedDoor, F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y), collision.code, M11_DM1_ViewportSquareIsOpenPc34(closedDoor.square)); ok &= expect_int("open door collision passable", collision.code, DM1_COLLISION_PASSABLE); ok &= expect_int("open door movement passability", F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y), 1); ok &= expect_int("open door overlay open", M11_DM1_ViewportSquareIsOpenPc34(closedDoor.square), 1); dungeon.tiles[closedDoor.mapIndex].squareData[tile_index(&dungeon, closedDoor.mapIndex, closedDoor.x, closedDoor.y)] = savedDoorSquare; closedDoor.square = savedDoorSquare; }
    if (openFakewall.found) { (void)DM1_V1_Collision_QuerySquare(&dungeon, openFakewall.mapIndex, openFakewall.x, openFakewall.y, &collision); print_case("open_fakewall", &openFakewall, F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, openFakewall.mapIndex, openFakewall.x, openFakewall.y), collision.code, M11_DM1_ViewportSquareIsOpenPc34(openFakewall.square)); ok &= expect_int("open fakewall passable", F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, openFakewall.mapIndex, openFakewall.x, openFakewall.y), 1); ok &= expect_int("open fakewall overlay corridor", M11_DM1_ViewportEffectiveElementForSquarePc34(openFakewall.square), DUNGEON_ELEMENT_CORRIDOR); }
    if (closedFakewall.found) { (void)DM1_V1_Collision_QuerySquare(&dungeon, closedFakewall.mapIndex, closedFakewall.x, closedFakewall.y, &collision); print_case("closed_fakewall", &closedFakewall, F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, closedFakewall.mapIndex, closedFakewall.x, closedFakewall.y), collision.code, M11_DM1_ViewportSquareIsOpenPc34(closedFakewall.square)); ok &= expect_int("closed fakewall overlay wall", M11_DM1_ViewportEffectiveElementForSquarePc34(closedFakewall.square), DUNGEON_ELEMENT_WALL); ok &= expect_int("closed fakewall wall-like", M11_DM1_ViewportSquareIsWallLikePc34(closedFakewall.square), 1); }
    if (buttonDoor.found) { ok &= expect_int("button door has decoded button", things.doors[buttonDoor.doorIndex].button, 1); ok &= expect_true("button door has adjacent party cell", place_party_adjacent_to(&dungeon, buttonDoor.mapIndex, buttonDoor.x, buttonDoor.y, &party)); ok &= expect_int("button door click accepted", DM1_V1_Door_ProcessClick(&dungeon, &things, &party, &click), 1); ok &= expect_int("button door click gate", click.doorHasButton, 1); ok &= expect_int("button door click target open", click.newDoorState, DM1_DOOR_STATE_OPEN); print_case("door_button_runtime", &buttonDoor, F0706_MOVEMENT_IsSquarePassable_Compat(&dungeon, buttonDoor.mapIndex, buttonDoor.x, buttonDoor.y), click.code, M11_DM1_ViewportSquareIsOpenPc34(buttonDoor.square)); }
    F0504_DUNGEON_FreeThingData_Compat(&things); F0500_DUNGEON_FreeDatHeader_Compat(&dungeon); printf("result=%s\n", ok ? "PASS" : "FAIL"); return ok ? 0 : 1;
}
