#include "dm2_v1_gdat_wall_trim_receipt.h"
#include <string.h>
static uint32_t h(uint32_t v,const void*p,size_t n){const uint8_t*b=p;while(n--){v^=*b++;v*=16777619u;}return v;}
static int same_surface(const DM2_V1_ViewportSurfaceSnapshot*a,const DM2_V1_ViewportSurfaceSnapshot*b){return a&&b&&a->framebuffer==b->framebuffer&&a->width==b->width&&a->height==b->height&&a->stride==b->stride&&a->resolution==b->resolution&&a->generation==b->generation;}
static uint32_t wall_hash(const DM2_V1_GdatWallM11CommandPlan*w){uint32_t v=2166136261u;uint8_t i;if(!w||!w->command_count||w->command_count>DM2_V1_GDAT_WALL_M11_COMMAND_MAX)return 0;for(i=0;i<w->command_count;i++){const DM2_V1_GdatWallM11Command*c=&w->commands[i];if(!c->raw_hash||!c->decoded_hash||!c->palette_hash||!c->material_receipt_hash||!c->geometry_hash||!c->rect_table_hash||!c->rect_row_hash||!c->metadata_hash)return 0;v=h(v,&c->raw_hash,4);v=h(v,&c->decoded_hash,4);v=h(v,&c->palette_hash,4);v=h(v,&c->material_receipt_hash,4);v=h(v,&c->geometry_hash,4);}return v?v:1;}
int dm2_v1_gdat_wall_trim_receipt_build(const DM2_V1_GdatSceneM11CommandPlan*s,const DM2_V1_GdatWallM11CommandPlan*w,const DM2_V1_ViewportState*o,uint8_t d,uint16_t x,uint16_t y,uint16_t width,uint16_t height,DM2_V1_GdatWallTrimReceipt*out){DM2_V1_ViewportSurfaceSnapshot surface;uint16_t word;uint32_t v=2166136261u,wh=wall_hash(w);if(!out)return 0;
    memset(out,0,sizeof(*out));if(!s||!w||!o||!s->valid||!w->valid||!wh||wh!=w->command_hash||s->graphicsset!=w->graphicsset||(d!=1&&d!=2)||!dm2_v1_viewport_surface_snapshot(o,&surface)||!surface.framebuffer||!surface.width||!surface.height||!surface.stride||x>surface.width||y>surface.height||width>surface.width-x||height>surface.height-y)return 0;word=d==1?s->trim_wall_d1:s->trim_wall_d2;if(!(d==1?s->trim_wall_d1_present:s->trim_wall_d2_present))return 0;out->valid=out->no_draw=1;out->depth=d;out->graphicsset=s->graphicsset;out->trim_word=word;out->left=x;out->top=y;out->right=(uint16_t)(surface.width-x-width);out->bottom=(uint16_t)(surface.height-y-height);out->wall_material_hash=wh;out->scene_identity_hash=s->command_hash;out->surface=surface;v=h(v,&d,1);v=h(v,&word,2);v=h(v,&wh,4);v=h(v,&out->left,2);v=h(v,&out->top,2);v=h(v,&out->right,2);v=h(v,&out->bottom,2);v=h(v,&surface.generation,4);out->identity_hash=v?v:1;return 1;}
int dm2_v1_gdat_wall_trim_m11_receipt_build(const DM2_V1_GdatWallTrimReceipt*t,const DM2_V1_GdatWallM11CommandPlan*w,uint8_t i,const DM2_V1_Dm2ViewportM11CompositionReceipt*c,const DM2_V1_ViewportState*o,DM2_V1_GdatWallTrimM11Receipt*out){DM2_V1_ViewportSurfaceSnapshot surface;const DM2_V1_GdatWallM11Command*x;uint32_t wh=wall_hash(w),v=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));/* c_gui_vp.cpp:695-719: QUERY_TEMP_PICST(0x40,0x40,flip,...,0x2be+cell). */if(!t||!w||!c||!o||!t->valid||!t->no_draw||i>=w->command_count||!w->valid||!wh||wh!=w->command_hash||wh!=t->wall_material_hash||!c->valid||!c->no_draw||c->wall_command_hash!=wh||!c->identity_hash||!dm2_v1_viewport_surface_snapshot(o,&surface)||!same_surface(&surface,&t->surface)||!same_surface(&surface,&c->surface_before)||!same_surface(&surface,&c->surface_after))return 0;x=&w->commands[i];if(!x->pixels||!x->width||!x->height||!x->raw_hash||!x->decoded_hash||!x->palette_hash||!x->material_receipt_hash||!x->geometry_hash||x->rect_number!=(uint16_t)(0x2beu+x->view_square))return 0;out->valid=out->no_draw=1;out->view_square=x->view_square;out->normal_scale=1;out->source_flip=x->mirror_flip;out->movement_offset_y=x->movement_query_offset_y;out->rect_number=x->rect_number;out->trim_identity_hash=t->identity_hash;out->wall_material_hash=wh;out->composition_identity_hash=c->identity_hash;v=h(v,&out->trim_identity_hash,4);v=h(v,&wh,4);v=h(v,&out->composition_identity_hash,4);v=h(v,&out->rect_number,2);v=h(v,&out->source_flip,1);v=h(v,&out->movement_offset_y,1);out->identity_hash=v?v:1;return 1;}
