#include "dm2_v1_gdat_stairs_side_m11_receipt.h"
#include <string.h>

static const uint16_t s_rect[18]={0xffff,0xffff,0x340,0x340,0x341,0x341,0xffff,0xffff,0x33e,0x33c,0x33f,0x33d,0xffff,0xffff,0x33a,0x33a,0x33b,0x33b};
static const uint8_t s_field[18]={0xff,0xff,0xcd,0xc7,0xce,0xc8,0xff,0xff,0xcf,0xc9,0xd0,0xca,0xff,0xff,0xd1,0xcb,0xd2,0xcc};
static uint32_t hb(uint32_t h,const uint8_t*p,size_t n){size_t i;for(i=0;i<n;i++){h^=p[i];h*=16777619u;}return h;}
static uint16_t le(const uint8_t*p){return (uint16_t)p[0]|((uint16_t)p[1]<<8);}
static const uint8_t *row(const uint8_t*t,size_t n,uint16_t w){uint16_t g,i;size_t o;if(!t||n<4||le(t)!=0xfc0d)return NULL;g=le(t+2);if(!g||(size_t)g>(n-4)/4)return NULL;o=4+(size_t)g*4;for(i=0;i<g;i++){uint16_t a=le(t+4+(size_t)i*4),b=le(t+6+(size_t)i*4);size_t c=b>=a?(size_t)(b-a+1):0;if(!c||c>(n-o)/8)return NULL;if(w>=a&&w<=b)return t+o+(size_t)(w-a)*8;o+=c*8;}return NULL;}
int dm2_v1_gdat_stairs_side_source_receipt(uint8_t cell,uint16_t state,uint8_t gs,uint16_t light,DM2_V1_GdatStairsSideSourceReceipt*out){uint16_t i;uint32_t h=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));/* c_gui_vp.cpp:540-565; dm2data.cpp:275-287. */if(cell>8||light>640)return 0;i=(uint16_t)cell*2u+(state!=0);if(s_rect[i]==0xffff||s_field[i]==0xff)return 0;out->valid=out->no_draw=1;out->view_cell=cell;out->state_variant=state!=0;out->graphicsset=gs;out->field=s_field[i];out->rect_number=s_rect[i];out->light_parameter=light;h=hb(h,(const uint8_t*)&out->view_cell,1);h=hb(h,&out->state_variant,1);h=hb(h,&out->graphicsset,1);h=hb(h,&out->field,1);h=hb(h,(const uint8_t*)&out->rect_number,2);h=hb(h,(const uint8_t*)&light,2);out->identity_hash=h?h:1;return 1;}
int dm2_v1_gdat_stairs_side_material_receipt_build(const DM2_V1_AssetLoader*l,const DM2_V1_GdatStairsSideSourceReceipt*s,DM2_V1_GdatStairsSideMaterialReceipt*out){DM2_V1_GdatStairsSideMaterialReceipt c;uint8_t*p;int w=0,h=0;uint32_t x=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));if(!l||!s||!s->valid||!s->identity_hash)return 0;
    memset(&c,0,sizeof(c));c.source=*s;if(!dm2_v1_query_gdat_summary_image_receipt(l,DM2_GDAT_CATEGORY_GRAPHICSSET,s->graphicsset,s->field,&c.summary)||!c.summary.accepted||c.summary.gdat_bypassed_for_ff||c.summary.colors!=16||!c.summary.palette_hash||!dm2_v1_gdat_image_raw_material_receipt(l,DM2_GDAT_CATEGORY_GRAPHICSSET,s->graphicsset,s->field,&c.raw_material)||!c.raw_material.receipt_hash)return 0;p=dm2_v1_asset_load_image_field(l,DM2_GDAT_CATEGORY_GRAPHICSSET,s->graphicsset,s->field,&w,&h,&c.format);if(!p||w<=0||h<=0||c.format!=DM2_IMG_FMT_U4||(size_t)w>SIZE_MAX/(size_t)h){dm2_v1_asset_free_pixels(p);return 0;}c.valid=c.no_draw=1;c.indexed_pixels=p;c.width=(uint16_t)w;c.height=(uint16_t)h;c.pixel_stride=(uint16_t)w;c.indexed_pixel_count=(uint32_t)((size_t)w*(size_t)h);memcpy(c.palette16,c.summary.palette16,16);c.decoded_hash=hb(2166136261u,p,c.indexed_pixel_count);c.palette_hash=hb(2166136261u,c.palette16,16);if(!c.decoded_hash||!c.palette_hash){dm2_v1_asset_free_pixels(p);return 0;}x=hb(x,(const uint8_t*)&s->identity_hash,4);x=hb(x,(const uint8_t*)&c.summary.receipt_hash,4);x=hb(x,(const uint8_t*)&c.raw_material.receipt_hash,4);x=hb(x,(const uint8_t*)&c.decoded_hash,4);x=hb(x,(const uint8_t*)&c.palette_hash,4);c.identity_hash=x?x:1;*out=c;return 1;}
int dm2_v1_gdat_stairs_side_raw4_receipt_build(const DM2_V1_AssetLoader*l,const DM2_V1_GdatStairsSideMaterialReceipt*m,DM2_V1_GdatStairsSideRaw4Receipt*out){const uint8_t*t,*r;size_t n=0;uint32_t h=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));if(!l||!m||!m->valid)return 0;t=dm2_v1_asset_load_typed_sized(l,DM2_GDAT_CATEGORY_INTERFACE_GENERAL,0,DM2_GDAT_ENTRY_TYPE_RAW4,0,&n);r=row(t,n,m->source.rect_number);if(!r||le(r)!=1||le(r+2)!=0)return 0;out->valid=out->no_draw=1;out->rect_number=m->source.rect_number;out->destination_x=(int16_t)le(r+4);out->destination_y=(int16_t)le(r+6);out->width=m->width;out->height=m->height;out->material_identity_hash=m->identity_hash;out->raw4_table_hash=hb(2166136261u,t,n);out->raw4_row_hash=hb(2166136261u,r,8);h=hb(h,(const uint8_t*)&out->material_identity_hash,4);h=hb(h,(const uint8_t*)&out->raw4_table_hash,4);h=hb(h,(const uint8_t*)&out->raw4_row_hash,4);out->identity_hash=h?h:1;return out->raw4_table_hash&&out->raw4_row_hash;}
int dm2_v1_gdat_stairs_side_m11_receipt_build(const DM2_V1_GdatStairsSideMaterialReceipt*m,const DM2_V1_GdatStairsSideRaw4Receipt*r,const DM2_V1_Dm2ViewportM11CompositionReceipt*c,const DM2_V1_ViewportState*o,DM2_V1_GdatStairsSideM11Receipt*out){DM2_V1_ViewportSurfaceSnapshot s;uint32_t h=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));/* DRAW_DUNGEON_GRAPHIC's B073/DRAW_PICST is still no-draw. */if(!m||!r||!c||!o||!m->valid||!r->valid||r->material_identity_hash!=m->identity_hash||!c->valid||!c->no_draw||!c->session_identity||!c->data_epoch||!c->identity_hash||!dm2_v1_viewport_surface_snapshot(o,&s)||memcmp(&s,&c->surface_before,sizeof(s))||memcmp(&s,&c->surface_after,sizeof(s)))return 0;out->valid=out->no_draw=1;out->indexed_pixels=m->indexed_pixels;out->width=m->width;out->height=m->height;out->pixel_stride=m->pixel_stride;out->indexed_pixel_count=m->indexed_pixel_count;out->palette_hash=m->palette_hash;out->material_identity_hash=m->identity_hash;out->raw4_identity_hash=r->identity_hash;out->session_identity=c->session_identity;out->data_epoch=c->data_epoch;out->composition_identity_hash=c->identity_hash;out->surface_before=out->surface_after=s;h=hb(h,(const uint8_t*)&out->material_identity_hash,4);h=hb(h,(const uint8_t*)&out->raw4_identity_hash,4);h=hb(h,(const uint8_t*)&out->palette_hash,4);h=hb(h,(const uint8_t*)&out->session_identity,4);h=hb(h,(const uint8_t*)&out->data_epoch,4);h=hb(h,(const uint8_t*)&s.generation,4);out->identity_hash=h?h:1;return 1;}
int dm2_v1_gdat_stairs_side_dungeon_graphic_receipt_build(const DM2_V1_GdatStairsSideMaterialReceipt*m,const DM2_V1_GdatStairsSideRaw4Receipt*r,const DM2_V1_GdatStairsSideM11Receipt*q,DM2_V1_GdatStairsSideDungeonGraphicReceipt*out){uint32_t h=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));/* c_gui_vp.cpp:540-565 -> c_image.cpp:450-475. c_image.cpp:461 shifts only 0x2bc/0x2bd. */if(!m||!r||!q||!m->valid||!r->valid||!q->valid||!m->no_draw||!r->no_draw||!q->no_draw||!m->identity_hash||!r->identity_hash||!q->identity_hash||r->material_identity_hash!=m->identity_hash||q->material_identity_hash!=m->identity_hash||q->raw4_identity_hash!=r->identity_hash||m->source.rect_number==0x2bcu||m->source.rect_number==0x2bdu)return 0;out->valid=out->no_draw=1;out->blit_mode=0;out->normal_scale=1;out->source_offset_is_zero=1;/* query_B073(image.palette, ddat.v1e12d2, alpha, -1, ...) lacks a live state receipt. */out->palette_transaction_unproven=1;out->alpha_mask=m->source.light_parameter;out->material_identity_hash=m->identity_hash;out->raw4_identity_hash=r->identity_hash;out->m11_identity_hash=q->identity_hash;h=hb(h,(const uint8_t*)&out->material_identity_hash,4);h=hb(h,(const uint8_t*)&out->raw4_identity_hash,4);h=hb(h,(const uint8_t*)&out->m11_identity_hash,4);h=hb(h,(const uint8_t*)&out->alpha_mask,2);h=hb(h,&out->blit_mode,1);h=hb(h,&out->normal_scale,1);out->identity_hash=h?h:1;return 1;}
