#include "dm2_v1_gdat_door_button_d2_m11_consumer.h"
#include <string.h>
static uint32_t h(const uint8_t*p,size_t n){uint32_t x=2166136261u;while(n--){x^=*p++;x*=16777619u;}return x;}
static int ss(const DM2_V1_ViewportSurfaceSnapshot*a,const DM2_V1_ViewportSurfaceSnapshot*b){return a&&b&&a->framebuffer==b->framebuffer&&a->width==b->width&&a->height==b->height&&a->stride==b->stride&&a->resolution==b->resolution&&a->generation==b->generation;}
static uint16_t stretch(uint16_t n){return (uint16_t)(((uint32_t)n*0x2bu+0x15u)>>6);}
static int ok(const DM2_V1_GdatDoorButtonD2M11Receipt*r,const DM2_V1_GdatDoorOverlayM11CommandPlan*p,const DM2_V1_Dm2ViewportM11CompositionReceipt*c,const DM2_V1_ViewportState*o,DM2_V1_ViewportSurfaceSnapshot*out){DM2_V1_ViewportSurfaceSnapshot s;const DM2_V1_GdatDoorOverlayM11Command*q;if(!r||!p||!c||!o||!r->valid||!r->identity_hash||!p->valid||r->command_index>=p->command_count||!c->valid||!c->no_draw||!c->identity_hash||!c->session_identity||!c->data_epoch||c->door_command_hash!=p->command_hash||r->door_hash!=p->command_hash||!o->gdat_scene_control_ready||!o->gdat_scene_control_hash||o->gdat_scene_control_hash!=r->scene_hash||c->scene_command_hash!=r->scene_hash||r->composition_hash!=c->identity_hash||!dm2_v1_viewport_surface_snapshot(o,&s)||!ss(&s,&c->surface_before)||!ss(&s,&c->surface_after)||s.generation!=r->surface_generation)return 0;q=&p->commands[r->command_index];if(q->kind!=DM2_V1_GDAT_DOOR_BUTTON||q->category!=DM2_GDAT_CATEGORY_DOOR_BUTTONS||q->view_square!=DM2_SQ_D2C||q->entry_index||!(q->field==0u||q->field==5u)||q->field!=r->field||q->rect_number!=0x7a0u||q->rect_number!=r->rect_number||q->stretch_dual!=0x2bu||q->mirror_flip||!q->width||!q->height||q->source_x||q->source_y||q->source_width!=q->width||q->source_height!=q->height||q->rect_width!=stretch(q->width)||q->rect_height!=stretch(q->height)||q->rect_x!=r->x||q->rect_y!=r->y||q->rect_width!=r->width||q->rect_height!=r->height||!q->material_source_bytes||!q->material_source_byte_count||!q->material_receipt_hash||!q->raw_hash||!q->decoded_hash||!q->palette_hash||!q->geometry_hash||!q->rect_table_hash||!q->rect_row_hash||q->raw_hash!=r->raw_hash||q->decoded_hash!=r->decoded_hash||q->palette_hash!=r->palette_hash||q->geometry_hash!=r->geometry_hash||q->rect_table_hash!=r->table_hash||q->rect_row_hash!=r->row_hash||r->x<0||r->y<0||(uint32_t)r->x+r->width>s.width||(uint32_t)r->y+r->height>s.height||h(q->material_source_bytes,q->material_source_byte_count)!=q->raw_hash||h(q->pixels,(size_t)q->width*q->height)!=q->decoded_hash||h(q->palette16,16)!=q->palette_hash)return 0;if(out)*out=s;return 1;}
int dm2_v1_gdat_door_button_d2_m11_receipt_build(const DM2_V1_GdatDoorOverlayM11CommandPlan*p,uint8_t i,const DM2_V1_Dm2ViewportM11CompositionReceipt*c,const DM2_V1_ViewportState*o,DM2_V1_GdatDoorButtonD2M11Receipt*out){DM2_V1_GdatDoorButtonD2M11Receipt r;DM2_V1_ViewportSurfaceSnapshot s;const DM2_V1_GdatDoorOverlayM11Command*q;uint32_t x=2166136261u;if(!out)return 0;
    memset(out,0,sizeof(*out));if(!p||!c||!o||!p->valid||i>=p->command_count||!dm2_v1_viewport_surface_snapshot(o,&s))return 0;q=&p->commands[i];memset(&r,0,sizeof(r));r.valid=1;r.command_index=i;r.field=q->field;r.rect_number=q->rect_number;r.x=q->rect_x;r.y=q->rect_y;r.width=q->rect_width;r.height=q->rect_height;r.door_hash=p->command_hash;r.scene_hash=o->gdat_scene_control_hash;r.raw_hash=q->raw_hash;r.decoded_hash=q->decoded_hash;r.palette_hash=q->palette_hash;r.geometry_hash=q->geometry_hash;r.table_hash=q->rect_table_hash;r.row_hash=q->rect_row_hash;r.composition_hash=c->identity_hash;r.surface_generation=s.generation;x^=r.door_hash;x*=16777619u;x^=r.scene_hash;x*=16777619u;x^=r.raw_hash;x*=16777619u;x^=r.decoded_hash;x*=16777619u;x^=r.palette_hash;x*=16777619u;x^=r.geometry_hash;x*=16777619u;x^=r.composition_hash;x*=16777619u;r.identity_hash=x?x:1;if(!ok(&r,p,c,o,0))return 0;*out=r;return 1;}
int dm2_v1_gdat_door_button_d2_m11_consume(const DM2_V1_GdatDoorButtonD2M11Receipt*r,const DM2_V1_GdatDoorOverlayM11CommandPlan*p,const DM2_V1_Dm2ViewportM11CompositionReceipt*c,DM2_V1_ViewportState*o){DM2_V1_ViewportSurfaceSnapshot s;const DM2_V1_GdatDoorOverlayM11Command*q;if(!ok(r,p,c,o,&s))return 0;q=&p->commands[r->command_index];for(uint16_t y=0;y<r->height;y++){const uint8_t*src=q->pixels+(size_t)((uint32_t)y*q->height/r->height)*q->width;uint8_t*dst=s.framebuffer+(size_t)(r->y+y)*s.stride+r->x;for(uint16_t x=0;x<r->width;x++){uint8_t v=src[(uint32_t)x*q->width/r->width];if(v!=(uint8_t)o->gdat_scene_colorkey)dst[x]=q->palette16[v&15u];}}return 1;}
