#!/usr/bin/env python3
"""Generate the DM2 GDAT-key to canonical-English l10n bridge.

The input is the checked-in, reviewed gettext marker inventory.  It is not
game media and is used only at build time.  The generated table lets a
Japanese FM Towns disc remain the sole runtime data owner: Firestaff can map
an authenticated GDAT key to its canonical gettext msgid without requiring a
PC-English GRAPHICS.DAT at runtime.
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "po" / "dm2_source_strings.c"
OUTPUT = ROOT / "src" / "dm2" / "dm2_v1_i18n_builtin_overlay.inc"
ENTRY = re.compile(r"/\* GDAT (?P<keys>.*?) \*/\s*DM2_N_\((?P<text>.*?)\),$")
KEY = re.compile(r"0x([0-9a-fA-F]{2})/0x([0-9a-fA-F]{2})/0x([0-9a-fA-F]{2})")
STRING = re.compile(r'"(?:\\.|[^"\\])*"')


def decode_c_strings(expression: str) -> str:
    return "".join(ast.literal_eval(token) for token in STRING.findall(expression))


def quote_c(value: str) -> str:
    return '"' + value.encode("unicode_escape").decode("ascii").replace('"', r'\"') + '"'


def main() -> int:
    entries: dict[tuple[int, int, int], str] = {}
    for raw in SOURCE.read_text(encoding="utf-8").splitlines():
        match = ENTRY.search(raw)
        if not match:
            continue
        text = decode_c_strings(match.group("text"))
        for key in KEY.finditer(match.group("keys")):
            identity = tuple(int(part, 16) for part in key.groups())
            old = entries.setdefault(identity, text)
            if old != text:
                raise SystemExit(f"conflicting text for GDAT key {identity}")
    if not entries:
        raise SystemExit("no DM2 gettext markers found")
    rows = [
        "/* Generated by po/generate_dm2_builtin_l10n_overlay.py; do not edit. */",
        "static const DM2_V1_I18nBuiltinText g_builtin_english_text[] = {",
    ]
    for (category, index, field), text in sorted(entries.items()):
        rows.append(f"    {{{category:#04x}, {index:#04x}, {field:#04x}, {quote_c(text)}}},")
    rows.extend(["};", ""])
    OUTPUT.write_text("\n".join(rows), encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}: {len(entries)} keyed strings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
