#!/usr/bin/env bash
# Pass 47 — DOSBox capture harness for DM1 PC 3.4 English.
#
# Purpose
# -------
# Produce deterministic 320x200 VGA frame captures of the original DM1
# PC 3.4 English binary (DM.EXE) running under DOSBox, so they can be
# used as pixel-reference material for Pass 49-style viewport and
# side-panel overlays against Firestaff V1 captures.
#
# What this script DOES
# ---------------------
# - Stages DM1 PC 3.4 from the tracked archive
#   ``original-games/Game,Dungeon_Master,DOS,Software.7z`` into a scratch
#   directory under ``$OUT_DIR``.
# - Generates a deterministic, fixed-cycles, core-normal dosbox.conf
#   that disables dynamic cycles, fixes the machine to VGA, captures
#   screenshots to a known directory, and autoboots DM.EXE.
# - Prints exactly how to invoke DOSBox and where captures land.
#
# What this script DOES NOT do
# ----------------------------
# - It does not install DOSBox.  This is intentional: installing an
#   emulator is a host-level action that requires explicit user consent.
# - It does not drive keystrokes scripted inside the game -- DOSBox does
#   not provide a deterministic input-injection path on the CLI.  Input
#   scripting requires either DOSBox-X's ``autoexec`` keystroke feature
#   plus timed delays, or a KeyMapper recording.  Those are documented
#   as follow-up steps.
# - It does not claim the resulting captures match Firestaff pixel-
#   perfect; that is the job of Pass 49 overlay checks.
#
# Prereqs
# -------
# - ``7zz`` (installed as /opt/homebrew/bin/7zz on this host)
# - one of: ``dosbox``, ``dosbox-x``, ``dosbox-staging`` on PATH.
#   If none is found, the script stops and prints installation hints
#   for the user to run by hand (``brew install --cask dosbox-staging-app``).
#
# Artifacts
# ---------
# - ``$OUT_DIR/dm1pc34/`` (staged game files; not tracked)
# - ``$OUT_DIR/dosbox.conf`` (deterministic config)
# - ``$OUT_DIR/capture/`` (screenshots land here when DOSBox is started
#   with ``CTRL+F5``)
#
# Usage
# -----
#   scripts/dosbox_dm1_capture.sh                 # stage + show commands
#   scripts/dosbox_dm1_capture.sh --run           # stage + launch DOSBox
#   scripts/dosbox_dm1_capture.sh --out /tmp/dm1  # override $OUT_DIR
#   scripts/dosbox_dm1_capture.sh --multilingual  # use PC 3.4 Multilingual tree instead of the US-English tree
#
# Honesty
# -------
# This is a *harness*, not a fully automated capture pipeline.  The
# remaining automation gap (scripted keystroke sequences that land the
# party on a target square with a target facing) is documented in
# ``parity-evidence/pass47_reference_capture_tooling.md``.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${REPO}/verification-screens/dm1-dosbox-capture"
ARCHIVE="${REPO}/original-games/Game,Dungeon_Master,DOS,Software.7z"
GAME_SUBDIR="DungeonMasterPC34"
DO_RUN=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --run) DO_RUN=1 ; shift ;;
        --out) OUT_DIR="$2"; shift 2 ;;
        --multilingual) GAME_SUBDIR="DungeonMasterPC34Multilingual"; shift ;;
        -h|--help)
            sed -n '1,60p' "$0"
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

SEVENZ="$(command -v 7zz || command -v 7z || true)"
if [[ -z "$SEVENZ" ]]; then
    echo "ERROR: neither 7zz nor 7z is on PATH (needed to stage the DM1 archive)." >&2
    echo "HINT: brew install sevenzip" >&2
    exit 3
fi

if [[ ! -f "$ARCHIVE" ]]; then
    echo "ERROR: DM1 archive missing: $ARCHIVE" >&2
    exit 4
fi

DOSBIN=""
for candidate in dosbox dosbox-staging dosbox-x; do
    if command -v "$candidate" >/dev/null 2>&1; then
        DOSBIN="$(command -v "$candidate")"
        break
    fi
done

mkdir -p "$OUT_DIR"
STAGE_DIR="$OUT_DIR/$(basename "$GAME_SUBDIR")"
CAPTURE_DIR="$OUT_DIR/capture"
CONF_PATH="$OUT_DIR/dosbox.conf"

if [[ ! -f "$STAGE_DIR/DM.EXE" ]]; then
    echo "[pass-47] staging $GAME_SUBDIR into $STAGE_DIR"
    mkdir -p "$OUT_DIR"
    # Extract just the one directory we want, preserving path.
    ( cd "$OUT_DIR" && "$SEVENZ" x -y "$ARCHIVE" "$GAME_SUBDIR/*" >/dev/null )
else
    echo "[pass-47] $STAGE_DIR already staged"
fi
mkdir -p "$CAPTURE_DIR"

# Write a deterministic DOSBox config.  Notes:
#   - machine=vgaonly: force VGA so viewport palette matches G8150..G8156
#   - cycles=fixed 3000: low but constant; prevents auto-tune jitter
#   - core=normal: avoids dynamic recompilation differences
#   - captures path points into $CAPTURE_DIR so screenshots are easy to
#     find (DOSBox hotkey CTRL+F5 for a single frame, CTRL+ALT+F5 for
#     video).
cat > "$CONF_PATH" <<EOF
# Deterministic DOSBox config for DM1 PC 3.4 capture (Pass 47).
# Generated by scripts/dosbox_dm1_capture.sh -- do not edit by hand.

[sdl]
fullscreen=false
output=surface
autolock=false

[dosbox]
machine=vgaonly
captures=$CAPTURE_DIR
memsize=4

[cpu]
core=normal
cputype=386
cycles=fixed 3000

[render]
aspect=false
scaler=none

[mixer]
nosound=true

[speaker]
pcspeaker=false
tandy=off
disney=false

[autoexec]
mount c "$STAGE_DIR"
c:
cls
echo Pass 47 DM1 PC 3.4 capture harness.
echo Hotkeys: CTRL+F5 screenshot, CTRL+F9 quit, ALT+ENTER fullscreen.
echo Screenshots land in $CAPTURE_DIR
# NOTE: we intentionally do NOT auto-launch DM.EXE so the operator can
# reach menu/start screens deliberately and record exact-state captures.
# To launch manually, type: DM
EOF

echo "[pass-47] wrote $CONF_PATH"
echo "[pass-47] capture dir:  $CAPTURE_DIR"

if [[ -z "$DOSBIN" ]]; then
    cat <<EOF

No DOSBox binary was found on PATH.  The harness staged the game and
wrote a deterministic config, but cannot launch the emulator itself.

To install one (pick one, any of them works):

    brew install --cask dosbox-staging-app          # recommended
    brew install --cask dosbox-x-app                # full-featured alternative

After install, either:

    open -a 'DOSBox Staging' --args -conf $CONF_PATH

or (if the CLI binary is on PATH):

    dosbox -conf $CONF_PATH

Inside DOSBox:
    C:\\> DM
Use CTRL+F5 to screenshot to $CAPTURE_DIR.
EOF
    exit 0
fi

echo "[pass-47] found DOSBox binary: $DOSBIN"
if [[ $DO_RUN -eq 1 ]]; then
    echo "[pass-47] launching DOSBox"
    exec "$DOSBIN" -conf "$CONF_PATH"
else
    echo ""
    echo "To launch DOSBox with the deterministic config, run:"
    echo "    $DOSBIN -conf $CONF_PATH"
    echo "Then inside the DOSBox prompt type:"
    echo "    DM"
    echo "and use CTRL+F5 for screenshots into $CAPTURE_DIR."
fi
