#!/usr/bin/env python3
"""
generate_nexus_v1_asset_manifest.py
====================================
Scan a live Nexus data directory, generate a canonical asset manifest,
and update the verification suite doc with real file sizes.

This is run once when the disc image is available to lock the canonical
sizes. Until then, sizes are best-effort estimates from extraction logs.

Usage:
  python3 scripts/generate_nexus_v1_asset_manifest.py [data_dir]
  # defaults to ~/.firestaff/data/nexus/
"""

import sys
import os
import json
from pathlib import Path

def scan_directory(data_dir):
    """Scan directory, return {filename: size} dict."""
    result = {}
    names = sorted(entry.name for entry in os.scandir(data_dir) if entry.is_file())
    for name in names:
        path = data_dir / name
        result[name] = path.stat().st_size
    return result

def main():
    if len(sys.argv) > 1:
        data_dir = Path(sys.argv[1])
    else:
        home = os.environ.get("HOME", "")
        data_dir = Path(home) / ".firestaff" / "data" / "nexus"

    if not data_dir.is_dir():
        print(f"ERROR: data directory not found: {data_dir}", file=sys.stderr)
        sys.exit(1)

    files = scan_directory(data_dir)
    print(f"Scanned {len(files)} files in {data_dir}")
    print()

    # Categorize by extension / naming pattern
    dgn   = {k: v for k, v in files.items() if k.startswith("LEV") and k.endswith(".DGN")}
    mns   = {k: v for k, v in files.items() if k.endswith(".MNS")}
    sal   = {k: v for k, v in files.items() if k.endswith(".SAL")}
    maps  = {k: v for k, v in files.items() if k.endswith(".MAP")}
    slev  = {k: v for k, v in files.items() if k.startswith("SLEV") and k.endswith(".BIN")}
    smap  = {k: v for k, v in files.items() if k.startswith("SMAP") and k.endswith(".BIN")}
    avi   = {k: v for k, v in files.items() if k.endswith(".AVI")}
    core  = {k: v for k, v in files.items()
             if k in ("DM.BIN","0DMSTRT.BIN","TITLE.BIN","WARNING.BIN","GAMEOVER.BIN",
                      "FACE.BIN","DEATH.BIN","STONE.BIN","NBG3.BIN","POTEFT.BIN",
                      "RHIFIX.BIN","RLOWFIX.BIN","STABG.BIN","SWTCHR.BIN","MENU.BPK")}
    gfx   = {k: v for k, v in files.items()
             if k in ("TITLE.CG","LOGOBG.DG2","FONT256.S2D","ITEM.IBS","TM.BIN")}
    other = {k: v for k, v in files.items()
             if k not in dgn and k not in mns and k not in sal and k not in maps
             and k not in slev and k not in smap and k not in avi and k not in core
             and k not in gfx}

    for label, items in [("DGN (dungeon levels)", dgn),
                          (".MNS (creature models)", mns),
                          (".SAL (sound banks)", sal),
                          (".MAP (sound maps)", maps),
                          ("SLEV.BIN (level scripts)", slev),
                          ("SMAP.BIN (minimaps)", smap),
                          (".AVI (video)", avi),
                          ("Core game data", core),
                          ("Graphics", gfx),
                          ("Other", other)]:
        if items:
            total = sum(items.values())
            print(f"{label} — {len(items)} files, {total} bytes total:")
            for name, size in sorted(items.items()):
                print(f"  \"{name}\": {size},")
            print()

    # Write JSON manifest
    manifest = {
        "data_dir": str(data_dir),
        "total_files": len(files),
        "total_bytes": sum(files.values()),
        "files": files
    }
    out_path = Path(__file__).parent / "fixtures" / "nexus_v1_asset_manifest.json"
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"Manifest written to: {out_path}")

    # Also write as a Python dict literal for use in verify_nexus_v1_asset_manifest.py
    py_path = Path(__file__).parent / "fixtures" / "nexus_v1_asset_sizes.py"
    with open(py_path, "w") as f:
        f.write("# Auto-generated by generate_nexus_v1_asset_manifest.py\n")
        f.write("# Source: " + str(data_dir) + "\n")
        f.write("# Do not edit manually — re-run script when disc image is available\n\n")
        f.write("ACTUAL_SIZES = {\n")
        for name, size in sorted(files.items()):
            f.write(f'    "{name}": {size},\n')
        f.write("}\n")
    print(f"Size table written to: {py_path}")

if __name__ == "__main__":
    main()