#!/usr/bin/env python3
"""
verify_nexus_v1_asset_manifest.py
================================
Verify the Nexus V1 canonical asset manifest against a live data directory.

Checks:
  1. All 137 expected files exist
  2. File sizes match the manifest (within tolerance)
  3. LEV*.DGN files start with valid DGN header (Layout A or Layout B)
  4. *.MNS files have DMDF magic (0x444D4446) at byte 0
  5. STONE.BIN is exactly 4096 bytes (256 × 16-bit BGR555)

Exit codes:
  0  — all checks pass
  1  — one or more checks fail

Usage:
  python3 scripts/verify_nexus_v1_asset_manifest.py [data_dir]
  # data_dir defaults to ~/.firestaff/data/nexus/

Provenance: docs/NEXUS_FILE_CLASSIFICATION.md (137 files, disc T-9111G V1.003)
"""

import sys
import os
import struct
from pathlib import Path

import sys
import os
import struct
from pathlib import Path

# ── Load actual sizes from generated manifest (from disc image) ─────────
# Generated by: scripts/generate_nexus_v1_asset_manifest.py
# When disc image is present, this reflects real file sizes.
# When absent, falls back to canonical estimates from extraction logs.

ACTUAL_SIZES = None
try:
    from pathlib import Path as _P
    _sz_path = _P(__file__).parent / "fixtures" / "nexus_v1_asset_sizes.py"
    if _sz_path.is_file():
        import importlib.util, sys
        _spec = importlib.util.spec_from_file_location("nexus_sizes", str(_sz_path))
        _mod = importlib.util.module_from_spec(_spec)
        _spec.loader.exec_module(_mod)
        ACTUAL_SIZES = _mod.ACTUAL_SIZES
except Exception:
    pass

if ACTUAL_SIZES is None:
    # Fallback: canonical sizes from extraction logs (disc T-9111G V1.003)
    ACTUAL_SIZES = {
        # Dungeon Levels — 16 files
        "LEV00.DGN": 147456, "LEV01.DGN": 280576, "LEV02.DGN": 272384,
        "LEV03.DGN": 290816, "LEV04.DGN": 245760, "LEV05.DGN": 266240,
        "LEV06.DGN": 239616, "LEV07.DGN": 258048, "LEV08.DGN": 303104,
        "LEV09.DGN": 288768, "LEV10.DGN": 290816, "LEV11.DGN": 278528,
        "LEV12.DGN": 321536, "LEV13.DGN": 256000, "LEV14.DGN": 253952,
        "LEV15.DGN": 270336,

        # Creature Models (.MNS) — 30 files from real extraction
        "ANTMAN.MNS": 53768,   "BIGWORM.MNS": 53784,  "BORKETH.MNS": 67644,
        "CHAOS.MNS": 88572,    "DRA_ZOM.MNS": 83508,  "D_GOLD.MNS": 44000,
        "D_RED.MNS": 55276,    "D_SILVER.MNS": 41952, "GHOST.MNS": 48840,
        "GIGGLER.MNS": 43484,  "GOLEM.MNS": 48140,    "GRN_DRA.MNS": 56976,
        "H_HOUND.MNS": 46364,  "LAS_MON.MNS": 76232,   "LORD_RIB.MNS": 19500,
        "MINI_DRA.MNS": 35612, "MUMMY.MNS": 55420,     "OBAKE.MNS": 15280,
        "OITU.MNS": 46524,     "RAT.MNS": 57496,       "RED_DRA.MNS": 62256,
        "ROCKPILE.MNS": 57680, "SCORPION.MNS": 53052,   "SCREAMER.MNS": 29668,
        "SN_FLOOR.MNS": 49764, "SN_WALL.MNS": 43620,    "S_SHIELD.MNS": 31164,
        "S_SWORD.MNS": 49716,  "VEXIRK.MNS": 51640,    "WORM.MNS": 55832,

        # Sound banks — 16 files (variable sizes from real data)
        "SNDLEV00.SAL": 297082, "SNDLEV01.SAL": 297082, "SNDLEV02.SAL": 315126,
        "SNDLEV03.SAL": 357112, "SNDLEV04.SAL": 378192, "SNDLEV05.SAL": 335928,
        "SNDLEV06.SAL": 436904, "SNDLEV07.SAL": 350658, "SNDLEV08.SAL": 469710,
        "SNDLEV09.SAL": 416918, "SNDLEV10.SAL": 419550, "SNDLEV11.SAL": 390272,
        "SNDLEV12.SAL": 388508, "SNDLEV13.SAL": 393044, "SNDLEV14.SAL": 441498,
        "SNDLEV15.SAL": 374216,
        "SNDLEV00.MAP": 66,     "SNDLEV01.MAP": 66,     "SNDLEV02.MAP": 74,
        "SNDLEV03.MAP": 82,     "SNDLEV04.MAP": 82,     "SNDLEV05.MAP": 82,
        "SNDLEV06.MAP": 82,     "SNDLEV07.MAP": 82,     "SNDLEV08.MAP": 90,
        "SNDLEV09.MAP": 74,     "SNDLEV10.MAP": 82,     "SNDLEV11.MAP": 82,
        "SNDLEV12.MAP": 82,     "SNDLEV13.MAP": 82,     "SNDLEV14.MAP": 82,
        "SNDLEV15.MAP": 74,

        # Core game data — 15 files
        "DM.BIN": 555144,       "0DMSTRT.BIN": 39516,   "TITLE.BIN": 112216,
        "WARNING.BIN": 101256,  "GAMEOVER.BIN": 103024, "FACE.BIN": 45104,
        "DEATH.BIN": 4400,     "NBG3.BIN": 7168,      "STONE.BIN": 4400,
        "POTEFT.BIN": 3256,     "RHIFIX.BIN": 5448,     "RLOWFIX.BIN": 72332,
        "STABG.BIN": 53744,     "SWTCHR.BIN": 38640,   "MENU.BPK": 89060,

        # Graphics — 5 files
        "TITLE.CG": 167968,     "LOGOBG.DG2": 72198,   "FONT256.S2D": 25012,
        "ITEM.IBS": 100352,     "TM.BIN": 160044,

        # Level supplementary — 32 files
        "SLEV00.BIN": 2388,   "SLEV01.BIN": 4904,   "SLEV02.BIN": 5988,
        "SLEV03.BIN": 11660,  "SLEV04.BIN": 7124,   "SLEV05.BIN": 6336,
        "SLEV06.BIN": 6628,   "SLEV07.BIN": 7916,   "SLEV08.BIN": 10784,
        "SLEV09.BIN": 4452,   "SLEV10.BIN": 9600,   "SLEV11.BIN": 6532,
        "SLEV12.BIN": 8836,   "SLEV13.BIN": 3776,   "SLEV14.BIN": 3580,
        "SLEV15.BIN": 11272,
        "SMAP00.BIN": 22368,  "SMAP01.BIN": 17056,  "SMAP02.BIN": 22496,
        "SMAP03.BIN": 25056,  "SMAP04.BIN": 20640,  "SMAP05.BIN": 19360,
        "SMAP06.BIN": 19744,  "SMAP07.BIN": 23200,  "SMAP08.BIN": 30112,
        "SMAP09.BIN": 25504,  "SMAP10.BIN": 28768,  "SMAP11.BIN": 22624,
        "SMAP12.BIN": 21408,  "SMAP13.BIN": 17056,  "SMAP14.BIN": 19168,
        "SMAP15.BIN": 23328,

        # Video — 3 files
        "DMV0.AVI": 35968446, "DMV1.AVI": 29198172, "DMV2.AVI": 40956634,

        # Other — 5 files
        "SDDRVS.TSK": 26610,  "DMN_ABS.TXT": 182,   "DMN_BIB.TXT": 91,
        "DMN_CPY.TXT": 97,
    }

# Build manifest from actual sizes (all files in ACTUAL_SIZES)
MANIFEST = ACTUAL_SIZES


SIZE_TOLERANCE = 512  # bytes — allow small variance from extraction rounding


def check_dgn_header(path: Path) -> tuple[bool, str]:
    """Check DGN file header (Layout A or Layout B)."""
    try:
        with open(path, "rb") as f:
            data = f.read(4)
        if len(data) < 4:
            return False, "file too small for header"
        w = struct.unpack(">H", data[0:2])[0]
        h = struct.unpack(">H", data[2:4])[0]
        if 1 <= w <= 32 and 1 <= h <= 32:
            return True, f"Layout A: {w}x{h}"
        # Layout B: raw 32x32 grid — check file is at least 2048 bytes
        if path.stat().st_size >= 2048:
            return True, "Layout B: raw 32x32 grid at offset 0"
        return False, "file too small for Layout B (need >= 2048 bytes)"
    except Exception as e:
        return False, str(e)


def check_dmdf_magic(path: Path) -> tuple[bool, str]:
    """Check DMDF magic at byte 0 of .MNS file."""
    try:
        with open(path, "rb") as f:
            magic = f.read(4)
        if len(magic) < 4:
            return False, "file too small for magic"
        if magic == b"DMDF":
            return True, "DMDF magic valid"
        return False, f"bad magic: {magic.hex()}"
    except Exception as e:
        return False, str(e)


def main():
    # Determine data directory
    if len(sys.argv) > 1:
        data_dir = Path(sys.argv[1])
    else:
        home = os.environ.get("HOME", "")
        data_dir = Path(home) / ".firestaff" / "data" / "nexus"

    print(f"=== Nexus V1 Asset Manifest Verification ===")
    print(f"Data dir: {data_dir}")
    print()

    if not data_dir.is_dir():
        print(f"SKIP: data directory not found: {data_dir}")
        print("      (No disc image or extracted files present)")
        print("      Run with a valid --data-dir to verify against real files.")
        return 0  # Graceful skip — no game data is not a failure

    missing = []
    size_fail = []
    header_fail = []

    total = len(MANIFEST)
    present = 0

    for filename, expected_size in MANIFEST.items():
        path = data_dir / filename
        if not path.is_file():
            missing.append(filename)
            continue

        present += 1
        actual_size = path.stat().st_size

        # Size check (with tolerance)
        if abs(actual_size - expected_size) > SIZE_TOLERANCE:
            size_fail.append((filename, expected_size, actual_size))

        # Header checks for key formats
        if filename.startswith("LEV") and filename.endswith(".DGN"):
            ok, msg = check_dgn_header(path)
            if not ok:
                header_fail.append((filename, msg))
        elif filename.endswith(".MNS"):
            ok, msg = check_dmdf_magic(path)
            if not ok:
                header_fail.append((filename, msg))
        elif filename == "STONE.BIN":
            if actual_size != 4400:
                size_fail.append((filename, 4400, actual_size))

    # Report
    print(f"Expected files: {total}")
    print(f"Present files:  {present}")
    print(f"Missing:        {len(missing)}")
    print()

    if missing:
        print("MISSING FILES:")
        for f in sorted(missing):
            print(f"  - {f}")
        print()

    if size_fail:
        print("SIZE MISMATCHES:")
        for f, exp, act in sorted(size_fail):
            print(f"  - {f}: expected {exp}, got {act} (diff={act - exp:+d})")
        print()

    if header_fail:
        print("HEADER CHECK FAILURES:")
        for f, msg in sorted(header_fail):
            print(f"  - {f}: {msg}")
        print()

    if missing or size_fail or header_fail:
        print("RESULT: FAIL")
        return 1

    print("RESULT: PASS — all manifest checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())