#include "nexus_v1_structure3_face_texturing_capture_plan.h"
#include <string.h>
int nexus_v1_structure3_face_texturing_capture_plan_build(const Nexus_V1_Structure3FaceTexturingCapturePlanInput *input, Nexus_V1_Structure3FaceTexturingCaptureTarget *out)
{
    const Nexus_V1_DgnStructure1FDirectStaticMaterialCaptureTarget *s; const Nexus_V1_Structure1FCorpusTraceTarget *c; const Nexus_V1_Prs3DgnPlacementAdapterReceipt *p; const Nexus_V1_Prs3Vdp1CaptureReceipt *t; Nexus_V1_Structure3FaceTexturingCaptureTarget r;
    if(!out) return 0; memset(&r,0,sizeof(r)); r.capture_only=1;
    if(!input || !(s=input->structure1f) || !(c=input->corpus_target) || !(p=input->placement) || !(t=input->vdp1_trace) || !s->valid || !s->direct_face_material_bound || !s->capture_producer_required || !s->original_saturn_capture_required || !s->no_draw_only || s->fallback_visuals_permitted || !c->valid || !c->dgn_fnv1a64 || !c->descriptor_fnv1a64 || !c->mesh_fnv1a64 || !c->face_fnv1a64 || !c->original_saturn_trace_required || !c->no_draw_only || c->fallback_visuals_permitted || !p->valid || !p->trace_bound || !p->dgn_source_bound || !p->descriptor_envelope_bound || !p->command_coordinates_bound || !p->dgn_placement_observed || !p->no_draw_only || p->fallback_visuals_permitted || !p->prs3_bitmap_candidate_fnv1a64 || !p->palt_candidate_fnv1a64 || t->schema_version!=10U || !t->valid || !t->complete_capture || !t->dgn_placement_observed || !t->vdp1_texture_consumption_observed || !t->vdp1_command_consumption_observed || t->decoder_promoted || t->fallback_visuals_permitted || c->dgn_fnv1a64!=p->dgn_fnv1a64 || c->dgn_fnv1a64!=t->dgn_fnv1a64 || c->descriptor_index!=p->descriptor_index || c->descriptor_index!=t->dgn_descriptor_index || c->descriptor_fnv1a64!=p->descriptor_fnv1a64 || c->descriptor_fnv1a64!=t->dgn_descriptor_fnv1a64 || p->frame_sequence!=t->dgn_frame_sequence || p->command_sequence!=t->dgn_command_sequence || s->static_material.source_bytes_fnv1a64!=c->dgn_fnv1a64 || s->static_material.descriptor_target.descriptor_index!=(int)c->descriptor_index || s->static_material.descriptor_target.descriptor_bytes_fnv1a64!=c->descriptor_fnv1a64) { *out=r; return 0; }
    r.valid=r.original_saturn_capture_required=1; r.level_index=c->level_index; r.dgn_fnv1a64=c->dgn_fnv1a64; r.descriptor_index=c->descriptor_index; r.descriptor_fnv1a64=c->descriptor_fnv1a64; r.mesh_index=c->mesh_index; r.mesh_fnv1a64=c->mesh_fnv1a64; r.face_index=c->face_index; r.face_fnv1a64=c->face_fnv1a64; r.bitmap_candidate_fnv1a64=p->prs3_bitmap_candidate_fnv1a64; r.palette_candidate_fnv1a64=p->palt_candidate_fnv1a64; r.frame_sequence=p->frame_sequence; r.command_sequence=p->command_sequence; *out=r; return 1;
}
