#ifndef FIRESTAFF_CSB_V1_CSBWIN_VIEWPORT_GRAPHICS_MAP_H
#define FIRESTAFF_CSB_V1_CSBWIN_VIEWPORT_GRAPHICS_MAP_H

#include <stdint.h>
#include <stddef.h>

/* CSBWin CSBCode.cpp:2933-2940: Atari/CSBWin uses 13 records per wall set,
 * starting at 77. Entries 0..6 are door bitmaps, 7..12 wall bitmaps. */
enum {
    CSB_V1_CSBWIN_FLOORSET_FIRST_GRAPHIC = 75,
    CSB_V1_CSBWIN_FLOORSET_GRAPHIC_COUNT = 2,
    CSB_V1_CSBWIN_WALLSET_FIRST_GRAPHIC = 77,
    CSB_V1_CSBWIN_WALLSET_GRAPHIC_COUNT = 13,
    CSB_V1_CSBWIN_DOOR_GRAPHIC_COUNT = 7,
    CSB_V1_CSBWIN_WALL_GRAPHIC_COUNT = 6
};

/* CSBWin Viewport.cpp:2267-2279 maps each visible stone lane to one of six
 * source bitmaps. F3R2 is generated by MakeMirror from F3L2 at
 * CSBCode.cpp:2949-2952; it is not a fourteenth GRAPHICS.DAT wall record. */
typedef enum {
    CSB_V1_CSBWIN_VIEWPORT_WALL_F3L2 = 0,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F3L1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F3,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F3R1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F3R2,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F2L1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F2,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F2R1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F1L1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F1R1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F0L1,
    /* Viewport.cpp has a centre F0 rectangle too.  Unlike the surrounding
     * lanes it has no StdBitmapPointers wall source; it is composed by the
     * caller's local-cell path and must not borrow an adjacent bitmap. */
    CSB_V1_CSBWIN_VIEWPORT_WALL_F0,
    CSB_V1_CSBWIN_VIEWPORT_WALL_F0R1,
    CSB_V1_CSBWIN_VIEWPORT_WALL_COUNT
} CSB_V1_CSBWinViewportWall;

/* CSBWin CSBCode.cpp:10245 expands GRAPHICS.DAT item 0x22e directly to
 * Data::Byte7248 + 2. Data.h places wallRectangles[0] at source address
 * Byte3074. These entries are byte-coordinate RectPos records consumed by
 * TAG0088b2 via BltShapeToViewport: x1..y2 describe the inclusive viewport
 * destination; source_stride/source_height/source_x/source_y describe the
 * packed 4-bit source bitmap. They are not PC34 rectangles. */
#define CSB_V1_CSBWIN_LAYOUT_022E_GRAPHIC_INDEX 0x22eu
#define CSB_V1_CSBWIN_LAYOUT_022E_DECODED_SIZE 0x1270u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_RECTANGLE_OFFSET 3332u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_RECTANGLE_FAMILY_COUNT 9u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_RECTANGLE_STATE_COUNT 10u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_TRACK_RECTANGLE_OFFSET 4052u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_TRACK_RECTANGLE_COUNT 7u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_FRAME_RECTANGLE_OFFSET 4108u
#define CSB_V1_CSBWIN_LAYOUT_022E_DOOR_FRAME_RECTANGLE_COUNT 8u
#define CSB_V1_CSBWIN_LAYOUT_022E_WALL_RECTANGLE_OFFSET 4172u

typedef struct {
    uint8_t x1;
    uint8_t x2;
    uint8_t y1;
    uint8_t y2;
    uint8_t source_stride;
    uint8_t source_height;
    uint8_t source_x;
    uint8_t source_y;
} CSB_V1_CSBWinViewportProjectionRectangle;

typedef struct {
    int valid;
    /* Data.h / Viewport.cpp keeps these families immediately before
     * wallRectangles[]. They are source-owned TAG0088b2 RectPos records:
     * panel families are ordered F1R1, F1, F1L1, F2R1, F2, F2L1, F3R1,
     * F3, F3L1; each has ten door-state destinations. */
    CSB_V1_CSBWinViewportProjectionRectangle door_rectangles[
        CSB_V1_CSBWIN_LAYOUT_022E_DOOR_RECTANGLE_FAMILY_COUNT][
        CSB_V1_CSBWIN_LAYOUT_022E_DOOR_RECTANGLE_STATE_COUNT];
    CSB_V1_CSBWinViewportProjectionRectangle door_track_rectangles[
        CSB_V1_CSBWIN_LAYOUT_022E_DOOR_TRACK_RECTANGLE_COUNT];
    CSB_V1_CSBWinViewportProjectionRectangle door_frame_rectangles[
        CSB_V1_CSBWIN_LAYOUT_022E_DOOR_FRAME_RECTANGLE_COUNT];
    CSB_V1_CSBWinViewportProjectionRectangle rectangles[
        CSB_V1_CSBWIN_VIEWPORT_WALL_COUNT];
} CSB_V1_CSBWinViewportLayout022e;

/* One source-owned TAG0088b2 wall command after Viewport.cpp has selected
 * both its pWallBitmaps source and its wallRectangles destination. F0 is
 * intentionally absent: it is CSBWin's local-cell composition path, not a
 * GRAPHICS.DAT wall bitmap. */
typedef struct {
    CSB_V1_CSBWinViewportWall wall;
    uint16_t graphic_index;
    int mirrored;
    CSB_V1_CSBWinViewportProjectionRectangle projection;
} CSB_V1_CSBWinViewportWallDraw;

#define CSB_V1_CSBWIN_VIEWPORT_WALL_DRAW_COUNT \
    (CSB_V1_CSBWIN_VIEWPORT_WALL_COUNT - 1u)

typedef struct {
    int valid;
    size_t count;
    CSB_V1_CSBWinViewportWallDraw draws[
        CSB_V1_CSBWIN_VIEWPORT_WALL_DRAW_COUNT];
} CSB_V1_CSBWinViewportWallPlan;

/* Data.h's nine DoorRects families, in native memory and Viewport.cpp order. */
typedef enum {
    CSB_V1_CSBWIN_DOOR_PANEL_F1R1 = 0,
    CSB_V1_CSBWIN_DOOR_PANEL_F1,
    CSB_V1_CSBWIN_DOOR_PANEL_F1L1,
    CSB_V1_CSBWIN_DOOR_PANEL_F2R1,
    CSB_V1_CSBWIN_DOOR_PANEL_F2,
    CSB_V1_CSBWIN_DOOR_PANEL_F2L1,
    CSB_V1_CSBWIN_DOOR_PANEL_F3R1,
    CSB_V1_CSBWIN_DOOR_PANEL_F3,
    CSB_V1_CSBWIN_DOOR_PANEL_F3L1,
    CSB_V1_CSBWIN_DOOR_PANEL_COUNT
} CSB_V1_CSBWinDoorPanelFamily;

typedef struct {
    uint8_t bitmap_slot;
    int mirrored;
    CSB_V1_CSBWinViewportProjectionRectangle projection;
} CSB_V1_CSBWinDoorFrameDraw;

/* Source-owned static track/frame composition. bitmap_slot is pDoorBitmaps'
 * index (0 is the native mirror of 2; 1..7 are the seven source records in
 * CSBCode.cpp:2933-2940), so callers still resolve all pixels from
 * the original wall-set record rather than inventing a texture. */
typedef struct {
    int valid;
    size_t count;
    CSB_V1_CSBWinDoorFrameDraw draws[3];
} CSB_V1_CSBWinDoorFramePlan;

int csb_v1_csbwin_floor_ceiling_graphic_index(uint16_t floor_set,
                                               int ceiling,
                                               uint16_t *out_graphic_index);

/* CSBWin Bitmaps.cpp:187: two indexed 4-bit pixels occupy one source byte. */
int csb_v1_csbwin_packed_byte_width(uint16_t pixel_width,
                                    uint16_t *out_byte_width);

int csb_v1_csbwin_viewport_graphic_index(uint16_t wall_set,
                                          uint16_t slot,
                                          uint16_t *out_graphic_index);

/* CSBWin Code390e.cpp::ReadGraphicsForLevel initializes DoorGraphic[3][2]
 * from the current map's Door1Type/Door2Type selectors. For each door type
 * it reads 108 + 3 * DoorSet .. +2, storing the first value at F3, the
 * second at F2 and the third at F1. `nearness` is Viewport.cpp's
 * StdDoorGraphics ordinal: F1=0, F2=1, F3=2. */
int csb_v1_csbwin_door_panel_graphic_index(uint16_t door_set,
                                            uint8_t door_type,
                                            uint8_t nearness,
                                            uint16_t *out_graphic_index);

/* Resolves the GRAPHICS.DAT wall slot and whether CSBWin's `MakeMirror`
 * must reflect it before its native viewport projection. */
int csb_v1_csbwin_viewport_wall_source(uint16_t wall_set,
                                        CSB_V1_CSBWinViewportWall wall,
                                        uint16_t *out_graphic_index,
                                        int *out_mirrored);

/* CSBWin Viewport.cpp:2304-2317 selects one of the fourteen byte-coordinate
 * `wallRectangles[]` entries for TAG0088b2.  This mapping is deliberately
 * separate from the source-bitmap mapping: F3L2/F3R2 use 13/12 while their
 * shared source bitmap is mirrored only on the right. */
int csb_v1_csbwin_viewport_wall_projection_rectangle(
    CSB_V1_CSBWinViewportWall wall, uint8_t *out_rectangle_index);

int csb_v1_csbwin_viewport_layout_022e_decode(
    const uint8_t *decoded_graphic, size_t decoded_size,
    CSB_V1_CSBWinViewportLayout022e *out_layout);

int csb_v1_csbwin_viewport_layout_022e_read_graphics_dat(
    const char *graphics_dat_path, CSB_V1_CSBWinViewportLayout022e *out_layout);

/* Resolves the 13 pWallBitmaps-backed CSBWin wall commands for a single
 * WallSet. This is command metadata only: it does not invent a local F0
 * bitmap, infer dungeon visibility, or perform a host blit. */
int csb_v1_csbwin_viewport_build_wall_plan(
    uint16_t wall_set, const CSB_V1_CSBWinViewportLayout022e *layout,
    CSB_V1_CSBWinViewportWallPlan *out_plan);

/* CSBCode.cpp:4199-4235's exact DrawDoor panel selection. A closed door
 * (state 0) produces no panel. State 4/5 uses rect 0; partial states use
 * rect[state] for animated DB0 doors, otherwise the native split pairs. */
int csb_v1_csbwin_viewport_door_panel_projections(
    const CSB_V1_CSBWinViewportLayout022e *layout,
    CSB_V1_CSBWinDoorPanelFamily family, uint8_t door_state,
    int db0_mode, const CSB_V1_CSBWinViewportProjectionRectangle **out_first,
    const CSB_V1_CSBWinViewportProjectionRectangle **out_second);

/* Viewport.cpp:2281-2289, 2378-2404. Builds the static track/frame commands
 * that surround a door panel at its native lane. F3L1/F3R1 only carry their
 * side frame; F1/F2 lateral lanes only carry tracks. */
int csb_v1_csbwin_viewport_build_door_frame_plan(
    const CSB_V1_CSBWinViewportLayout022e *layout,
    CSB_V1_CSBWinDoorPanelFamily family,
    CSB_V1_CSBWinDoorFramePlan *out_plan);

/* TAG0088b2 accepts inclusive screen coordinates and a packed source row
 * stride. CSBWin's F0 local-cell rectangle is the deliberate no-source
 * exception; otherwise source_x must fit inside the stride measured as two
 * pixels per byte. */
int csb_v1_csbwin_viewport_projection_rectangle_is_valid(
    const CSB_V1_CSBWinViewportProjectionRectangle *rectangle);

#endif
