#ifndef FIRESTAFF_DM1_V1_VIEWPORT_FAKEWALL_PC34_COMPAT_H
#define FIRESTAFF_DM1_V1_VIEWPORT_FAKEWALL_PC34_COMPAT_H

int M11_DM1_ViewportEffectiveElementForSquarePc34(unsigned char square);
int M11_DM1_ViewportSquareIsWallLikePc34(unsigned char square);
int M11_DM1_ViewportSquareIsOpenPc34(unsigned char square);
int M11_DM1_ViewportSquareHasFloorOrnamentPathPc34(unsigned char square);

#endif
