#ifndef FIRESTAFF_DM1_V1_CHAMPION_RUNTIME_SOURCE_RECEIPT_PC34_COMPAT_H
#define FIRESTAFF_DM1_V1_CHAMPION_RUNTIME_SOURCE_RECEIPT_PC34_COMPAT_H

#include "dm1_v1_champion_live_runtime_composition_evidence_pc34_compat.h"

#ifdef __cplusplus
extern "C" {
#endif

#define DM1_V1_CHAMPION_RUNTIME_SOURCE_MAX_HANDS_PC34 8

typedef struct Dm1V1ChampionRuntimeHandSourcePc34 {
    int championIndex;
    int handIndex;
    int graphicIndex;
    const uint8_t *originalPixels;
} Dm1V1ChampionRuntimeHandSourcePc34;

typedef struct Dm1V1ChampionRuntimeSourceReceiptPc34 {
    int valid;
    unsigned int tick;
    unsigned int generation;
    Dm1V1ChampionLiveRuntimeCompositionReceiptPc34 liveEvidence;
    Dm1V1ChampionTopRowAssetsReceiptPc34 topRowAssets;
    int handSourceCount;
    Dm1V1ChampionRuntimeHandSourcePc34
        handSources[DM1_V1_CHAMPION_RUNTIME_SOURCE_MAX_HANDS_PC34];
} Dm1V1ChampionRuntimeSourceReceiptPc34;

/* Consumes the admitted live original-material evidence and binds original
 * hand-slot sources C033/C034/C035 for each live C028 champion. No hand icon,
 * portrait, statusbar, or substitute material is generated by this layer. */
int dm1_v1_champion_runtime_source_receipt_pc34(
    const struct PartyState_Compat *party,
    int actingChampionOrdinal,
    const Dm1V1ChampionLiveRuntimeCompositionReceiptPc34 *liveEvidence,
    const Dm1V1ChampionTopRowAssetsReceiptPc34 *topRowAssets,
    Dm1V1ChampionRuntimeSourceReceiptPc34 *outReceipt);

const char *dm1_v1_champion_runtime_source_receipt_source_evidence_pc34(void);

#ifdef __cplusplus
}
#endif

#endif
