#ifndef FIRESTAFF_DM1_V1_VIEWPORT_FAKEWALL_PC34_COMPAT_H
#define FIRESTAFF_DM1_V1_VIEWPORT_FAKEWALL_PC34_COMPAT_H

int DM1_V1_Viewport_EffectiveElementForSquarePc34Compat(unsigned char square);
int DM1_V1_Viewport_SquareIsWallLikePc34Compat(unsigned char square);
int DM1_V1_Viewport_SquareIsOpenPc34Compat(unsigned char square);
int DM1_V1_Viewport_SquareHasFloorOrnamentPathPc34Compat(unsigned char square);

#endif
