#ifndef FIRESTAFF_DM2_V1_GDAT_DOOR_BUTTON_D0_M11_CONSUMER_H
#define FIRESTAFF_DM2_V1_GDAT_DOOR_BUTTON_D0_M11_CONSUMER_H
#include "dm2_v1_gdat_door_button_m11_consumer.h"
typedef DM2_V1_GdatDoorButtonM11Receipt DM2_V1_GdatDoorButtonD0M11Receipt;
int dm2_v1_gdat_door_button_d0_m11_receipt_build(const DM2_V1_GdatDoorOverlayM11CommandPlan*,uint8_t,const DM2_V1_Dm2ViewportM11CompositionReceipt*,const DM2_V1_ViewportState*,DM2_V1_GdatDoorButtonD0M11Receipt*);
int dm2_v1_gdat_door_button_d0_m11_consume(const DM2_V1_GdatDoorButtonD0M11Receipt*,const DM2_V1_GdatDoorOverlayM11CommandPlan*,const DM2_V1_Dm2ViewportM11CompositionReceipt*,DM2_V1_ViewportState*);
#endif
