#ifndef FIRESTAFF_DM2_V1_GDAT_MATERIAL_PALETTE_PAIR_RECEIPT_H
#define FIRESTAFF_DM2_V1_GDAT_MATERIAL_PALETTE_PAIR_RECEIPT_H
#include "dm2_v1_gdat_original_material_receipt.h"
typedef struct { int valid,no_draw; const uint8_t *material_bytes,*palette_bytes; uint16_t width,height,stride,palette_byte_count; uint32_t material_byte_count,material_hash,palette_hash,surface_generation,identity_hash; } DM2_V1_GdatMaterialPalettePairReceipt;
int dm2_v1_gdat_material_palette_pair_receipt_build(const DM2_V1_GdatOriginalMaterialReceipt *,const DM2_V1_GdatPaletteM11ConsumerReceipt *,const DM2_V1_ViewportState *,DM2_V1_GdatMaterialPalettePairReceipt *);
#endif
