#ifndef FIRESTAFF_MENU_INPUT_M12_H
#define FIRESTAFF_MENU_INPUT_M12_H

typedef enum {
    M12_MENU_INPUT_NONE = 0,
    M12_MENU_INPUT_UP,
    M12_MENU_INPUT_DOWN,
    M12_MENU_INPUT_LEFT,
    M12_MENU_INPUT_RIGHT,
    M12_MENU_INPUT_STRAFE_LEFT,
    M12_MENU_INPUT_STRAFE_RIGHT,
    /* v2.8.x: split turn-left/turn-right out of LEFT/RIGHT so the
     * arrow keys can mean strafe (matching the original DM1 PC 3.4
     * gameplay convention where arrow keys move the party forward /
     * back and strafe left / right, while Home/End turn).  Q/E on
     * the keyboard also map to TURN_LEFT/TURN_RIGHT. */
    M12_MENU_INPUT_TURN_LEFT,
    M12_MENU_INPUT_TURN_RIGHT,
    M12_MENU_INPUT_ACCEPT,
    M12_MENU_INPUT_BACK,
    M12_MENU_INPUT_ACTION,
    M12_MENU_INPUT_CYCLE_CHAMPION,
    M12_MENU_INPUT_VALUE_LEFT,
    M12_MENU_INPUT_VALUE_RIGHT,
    M12_MENU_INPUT_REST_TOGGLE,
    M12_MENU_INPUT_USE_STAIRS,
    M12_MENU_INPUT_PICKUP_ITEM,
    M12_MENU_INPUT_DROP_ITEM,
    M12_MENU_INPUT_SPELL_RUNE_1,
    M12_MENU_INPUT_SPELL_RUNE_2,
    M12_MENU_INPUT_SPELL_RUNE_3,
    M12_MENU_INPUT_SPELL_RUNE_4,
    M12_MENU_INPUT_SPELL_RUNE_5,
    M12_MENU_INPUT_SPELL_RUNE_6,
    M12_MENU_INPUT_SPELL_CAST,
    M12_MENU_INPUT_SPELL_CLEAR,
    M12_MENU_INPUT_USE_ITEM,
    M12_MENU_INPUT_MAP_TOGGLE,
    M12_MENU_INPUT_INVENTORY_TOGGLE,
    M12_MENU_INPUT_SAVE_GAME,
    M12_MENU_INPUT_FREEZE_TOGGLE,
    M12_MENU_INPUT_DISK_MENU,
    M12_MENU_INPUT_CHAMPION_1_INVENTORY,
    M12_MENU_INPUT_CHAMPION_2_INVENTORY,
    M12_MENU_INPUT_CHAMPION_3_INVENTORY,
    M12_MENU_INPUT_CHAMPION_4_INVENTORY,
    /* Runtime-only presentation panel. F10 opens it while a game view is
     * active; unlike the launcher settings, this never fabricates assets. */
    M12_MENU_INPUT_GRAPHICS_POPUP
} M12_MenuInput;

#endif
