#ifndef FIRESTAFF_REDMCSB_F1086_REPLACE_INTUITION_VECTORS_PC34_COMPAT_H
#define FIRESTAFF_REDMCSB_F1086_REPLACE_INTUITION_VECTORS_PC34_COMPAT_H

void redmcsb_f1086_replace_intuition_vectors_pc34_compat(void);
const char *redmcsb_f1086_replace_intuition_vectors_source_evidence_pc34(void);

#endif
