#ifndef THERON_V1_TRACK02_LATER_ROUTE_CANDIDATE_BATCH_ATTESTATION_H
#define THERON_V1_TRACK02_LATER_ROUTE_CANDIDATE_BATCH_ATTESTATION_H
#include "theron_v1_track02_later_route_candidate_campaign_index.h"
int theron_v1_track02_later_route_candidate_batch_attest(const Theron_V1Track02LaterRouteCandidateCampaignIndex *index,const Theron_V1Track02LaterRouteCandidateReceipt *requested,unsigned count,uint32_t epoch,Theron_V1Track02LaterRouteCandidateCampaignIndex*out);
int theron_v1_track02_later_route_candidate_batch_import(const char *path,const Theron_V1Track02LaterRouteCandidateCampaignIndex *index,uint32_t epoch,Theron_V1Track02LaterRouteCandidateCampaignIndex*out);
#endif
