#ifndef THERON_V1_TRACK02_LATER_ROUTE_CANDIDATE_CAMPAIGN_INDEX_H
#define THERON_V1_TRACK02_LATER_ROUTE_CANDIDATE_CAMPAIGN_INDEX_H
#include "theron_v1_track02_later_route_candidate_intake.h"
#define THERON_V1_TRACK02_LATER_ROUTE_CANDIDATE_MAX 16u
typedef struct { int valid; int capture_required_only; unsigned count; Theron_V1Track02LaterRouteCandidateReceipt entries[THERON_V1_TRACK02_LATER_ROUTE_CANDIDATE_MAX]; } Theron_V1Track02LaterRouteCandidateCampaignIndex;
int theron_v1_track02_later_route_candidate_campaign_index_build(const Theron_V1Track02LaterRouteCandidateReceipt *candidates,unsigned count,uint32_t epoch,Theron_V1Track02LaterRouteCandidateCampaignIndex*out);
int theron_v1_track02_later_route_candidate_campaign_index_current(const Theron_V1Track02LaterRouteCandidateCampaignIndex *index,uint32_t layout_epoch,Theron_V1Track02LaterRouteCandidateCampaignIndex *out);
#endif
