#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets-v2/manifests/firestaff-v2-wave1-vertical-slice.manifest.json"
OUT = ROOT / "m11_v2_vertical_slice_assets.h"

PALETTE = [
    (0, 0, 0),
    (0, 0, 170),
    (0, 170, 0),
    (0, 170, 170),
    (170, 0, 0),
    (170, 0, 170),
    (170, 85, 0),
    (170, 170, 170),
    (85, 85, 85),
    (85, 85, 255),
    (85, 255, 85),
    (85, 255, 255),
    (255, 85, 85),
    (255, 85, 255),
    (255, 255, 85),
    (255, 255, 255),
]

TARGETS = {
    "fs.v2.slice.viewport-frame.base": {
        "symbol": "viewport_frame_base",
        "png": "fs-v2-slice-viewport-frame-base.1080p.png",
        "size": (224, 136),
    },
    "fs.v2.slice.action-area.base": {
        "symbol": "action_area_base",
        "png": "fs-v2-slice-action-area-base.1080p.png",
        "size": (87, 45),
    },
    "fs.v2.slice.spell-area.base": {
        "symbol": "spell_area_base",
        "png": "fs-v2-spell-area-base.1080p.png",
        "size": (87, 25),
    },
    "fs.v2.slice.spell-area.rune-bed": {
        "symbol": "spell_area_rune_bed",
        "png": "fs-v2-spell-area-rune-bed.1080p.png",
        "size": (87, 25),
    },
    "fs.v2.slice.spell-area.highlight-overlay": {
        "symbol": "spell_area_highlight",
        "png": "fs-v2-spell-area-highlight-overlay.1080p.png",
        "size": (87, 25),
    },
    "fs.v2.slice.spell-area.active-overlay": {
        "symbol": "spell_area_active",
        "png": "fs-v2-spell-area-active-overlay.1080p.png",
        "size": (87, 25),
    },
    "fs.v2.slice.status-box.left-frame": {
        "symbol": "status_box_left",
        "png": "fs-v2-slice-status-box-left-frame.1080p.png",
        "size": (67, 29),
    },
    "fs.v2.slice.status-box.right-frame": {
        "symbol": "status_box_right",
        "png": "fs-v2-slice-status-box-right-frame.1080p.png",
        "size": (67, 29),
    },
    "fs.v2.slice.party-hud-cell.standard-base": {
        "symbol": "party_hud_cell_base",
        "png": "fs-v2-slice-party-hud-cell-standard-base.1080p.png",
        "size": (18, 18),
    },
    "fs.v2.slice.party-hud-cell.highlight-overlay": {
        "symbol": "party_hud_cell_highlight",
        "png": "fs-v2-slice-party-hud-cell-highlight-overlay.1080p.png",
        "size": (18, 18),
    },
}


def nearest_palette_index(rgba: tuple[int, int, int, int]) -> int:
    r, g, b, a = rgba
    if a < 32:
        return 0
    return min(
        range(len(PALETTE)),
        key=lambda i: (PALETTE[i][0] - r) ** 2 + (PALETTE[i][1] - g) ** 2 + (PALETTE[i][2] - b) ** 2,
    )


def main() -> None:
    manifest = json.loads(MANIFEST.read_text())
    assets = {asset["id"]: asset for asset in manifest["assets"]}

    lines: list[str] = [
        "/* Generated by tools/generate_v2_vertical_slice_header.py from the Wave 1 vertical-slice manifest. */",
        "#ifndef FIRESTAFF_M11_V2_VERTICAL_SLICE_ASSETS_H",
        "#define FIRESTAFF_M11_V2_VERTICAL_SLICE_ASSETS_H",
        "typedef struct { unsigned short width; unsigned short height; const unsigned char* pixels; } M11_V2SliceAsset;",
    ]

    for asset_id, spec in TARGETS.items():
        asset = assets[asset_id]
        derived_dir = ROOT / asset["paths"]["derivedDir"]
        png_path = derived_dir / spec["png"]
        image = Image.open(png_path).convert("RGBA").resize(spec["size"], Image.Resampling.LANCZOS)
        pixels = [nearest_palette_index(px) for px in image.getdata()]
        array_name = f"m11_v2_{spec['symbol']}_pixels"
        lines.append(f"static const unsigned char {array_name}[{len(pixels)}] = {{")
        for i in range(0, len(pixels), 24):
            lines.append("    " + ", ".join(str(v) for v in pixels[i:i + 24]) + ",")
        lines.append("};")
        lines.append(
            f"static const M11_V2SliceAsset m11_v2_{spec['symbol']} = "
            + "{"
            + f"{spec['size'][0]}, {spec['size'][1]}, {array_name}"
            + "};"
        )

    lines.append("#endif")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
