#!/usr/bin/env python3
"""Emit the native CP932 mapping from Python's standard-library codec.

These are character-encoding mappings, not game data or font glyphs.
Undefined byte pairs remain zero and are rejected by the native decoder.
"""
import sys

def main():
    leads = list(range(0x81, 0xa0)) + list(range(0xe0, 0xfd))
    trails = list(range(0x40, 0x7f)) + list(range(0x80, 0xfd))
    print("/* Generated by tools/generate_cp932_table.py using Python's cp932 codec.")
    print(" * 60 lead rows x 188 trail columns; zero means undefined. */")
    print("static const uint16_t fs_cp932_pairs[60 * 188] = {")
    values = []
    for lead in leads:
        for trail in trails:
            try:
                decoded = bytes([lead, trail]).decode("cp932", errors="strict")
                assert len(decoded) == 1 and ord(decoded) <= 0xffff
                values.append(ord(decoded))
            except UnicodeDecodeError:
                values.append(0)
    for offset in range(0, len(values), 12):
        print("    " + ", ".join(f"0x{x:04x}" for x in values[offset:offset+12]) + ",")
    print("};")

if __name__ == "__main__":
    main()
