#!/usr/bin/env python3
"""Verify the DM1 V2 graphics-pipeline source-isolation gate.

This is a bounded Phase 2 verifier: V2 may upscale, filter, and present the
source DM1 picture, but the V2 presentation buffers/config must stay isolated
from gameplay state. The gate ties the current V2 renderer/settings seam to the
local DM1 PC34 originals and the ReDMCSB palette/font/viewport anchors.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REDMCSB = Path.home() / ".openclaw/data/firestaff-redmcsb-source/ReDMCSB_WIP20210206/Toolchains/Common/Source"
DM1_CANONICAL = Path.home() / ".openclaw/data/firestaff-original-games/DM/_canonical/dm1"
VERIFY_OUT = ROOT / "parity-evidence/verification/dm1_v2_graphics_pipeline_source_isolation.json"

EXPECTED_DM1_SHA256 = {
    "GRAPHICS.DAT": "2c3aa836925c64c09402bafb03c645932bd03c4f003ad9a86542383b078ecf8e",
    "DUNGEON.DAT": "d90b6b1c38fd17e41d63682f8afe5ca3341565b5f5ddae5545f0ce78754bdd85",
    "TITLE": "adc7f1916eeef343849f23c047977d307495b29793b796a54aa427ba71dd3745",
}

REDMCSB_ANCHORS = [
    {
        "file": "COORD.C",
        "function": "G3016_s_LayoutData01 + viewport globals",
        "lineRange": "1654-1722",
        "why": "C007 viewport zone and PC34 viewport geometry stay 320x200 screen / 224x136 viewport / screen origin 0,33.",
        "needles": [
            "{ {  9,   0, 320, 200 }",
            "{  9,   0, 224, 136 }",
            "int16_t G2067_i_ViewportScreenX = 0;",
            "int16_t G2068_i_ViewportScreenY = 33;",
            "G2070_ViewportBitmapByteCount = 15232",
            "int16_t G2073_C224_ViewportPixelWidth = 224;",
            "int16_t G2074_C136_ViewportHeight = 136;",
        ],
    },
    {
        "file": "DRAWVIEW.C",
        "function": "F0097_DUNGEONVIEW_DrawViewport / VIDRV_09_BlitViewPort",
        "lineRange": "830-857",
        "why": "The source viewport bitmap is blitted through C007_ZONE_VIEWPORT, not through gameplay-state coordinates.",
        "needles": [
            "F0694_SetMultipleColorsInPalette(C00_LIGHT0);",
            "F0021_MAIN_BlitToScreen(G0296_puc_Bitmap_Viewport, C007_ZONE_VIEWPORT",
            "F0638_GetZone(C007_ZONE_VIEWPORT",
            "VIDRV_09_BlitViewPort",
        ],
    },
    {
        "file": "DRAWVIEW.C",
        "function": "F2172_",
        "lineRange": "1077-1100,1208-1213",
        "why": "Low-level viewport copy hard-pins height 136, width 224, and screen line 33.",
        "needles": [
            "{ /* Draw viewport to screen memory */",
            "LDA        #68          /* Height 136 pixels */",
            "56 word copy operations = 112 bytes = 224 pixels = viewport width",
            "STA        0x34a0,Y     /* Start of line 33 on screen.",
            "ADC        #224         /* Viewport pixel width */",
        ],
    },
    {
        "file": "DRAWVIEW.C",
        "function": "G8151_LIGHT0..G8156_LIGHT5 + G8176_PaletteTable",
        "lineRange": "97-195,408-419",
        "why": "Dungeon-view palette levels are source tables selected by palette index, not generated by V2 state.",
        "needles": [
            "COLOR_DEF G8151_LIGHT0[17]",
            "COLOR_DEF G8152_LIGHT1[17]",
            "COLOR_DEF G8156_LIGHT5[17]",
            "COLOR_DEF* G8176_PaletteTable",
            "G8151_LIGHT0,           /* 0 */",
            "G8156_LIGHT5,           /* 5 */",
        ],
    },
    {
        "file": "IMAGE.C",
        "function": "G2061_DungeonViewPaletteIndices / F0694_SetMultipleColorsInPalette",
        "lineRange": "12-14,140-144",
        "why": "Source palette selection uses explicit dungeon-view palette indices and video-driver palette calls.",
        "needles": [
            "int16_t G2061_DungeonViewPaletteIndices[6] = { 0, 1, 2, 3, 4, 5 };",
            "void F0694_SetMultipleColorsInPalette",
            "VIDRV_08_SetMultipleColorsInPalette",
        ],
    },
    {
        "file": "TEXT.C",
        "function": "G0357_puc_InterfaceAndScrollsFont / F0040_TEXT_Print",
        "lineRange": "33-35,372-514",
        "why": "The interface font is a source bitmap pointer and text printing walks 5-pixel glyph cells with 1-pixel spacing.",
        "needles": [
            "unsigned char* G0357_puc_InterfaceAndScrollsFont;",
            "void F0040_TEXT_Print(",
            "movea.l G0357_puc_InterfaceAndScrollsFont",
            "Address of the character in the font",
            "addq.w  #6,D3",
        ],
    },
    {
        "file": "COORD.C",
        "function": "text/font metrics",
        "lineRange": "1757-1760,1787-1789",
        "why": "PC34 text metrics are explicit source constants: 6x7 normal text, 8x8 inscriptions, 320-wide PC message row.",
        "needles": [
            "int16_t G2087_C6_TextCharacterWidth = 6;",
            "int16_t G2088_C7_TextLineHeight = 7;",
            "int16_t G2089_C8_InscriptionCharacterWidth = 8;",
            "int16_t G2090_C8_InscriptionLineHeight = 8;",
            "int16_t G2092_MessageAreaWidth = 320;",
        ],
    },
]

FIRESTAFF_REQUIRED = [
    ("include/dm1_v2_viewport_renderer_pc34.h", "#define DM1_V2_VIEWPORT_W 224"),
    ("include/dm1_v2_viewport_renderer_pc34.h", "#define DM1_V2_VIEWPORT_H 136"),
    ("include/dm1_v2_viewport_renderer_pc34.h", "DM1_V2_ViewportCompositionInput"),
    ("include/dm1_v2_viewport_renderer_pc34.h", "DM1_V2_DungeonDatState"),
    ("include/dm1_v2_viewport_renderer_pc34.h", "DM1_V2_ViewportState"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "V1 320x200 indexed -> EPX 2x -> palette RGBA -> present"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "Panel (320x64) upscaled separately from viewport (224x136)"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "v21_viewport_set_palette"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "v21_viewport_get_v1_framebuffer"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "v21_inscription_render_overlay"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "char_w = 6 * scale"),
    ("src/dm1v2/dm1_v2_viewport_renderer_pc34.c", "char_h = 8 * scale"),
    ("src/dm1v2/dm1_v2_settings_pc34.c", "settings->palette_enhanced = 0"),
    ("src/dm1v2/dm1_v2_settings_pc34.c", "no bilinear on indexed data"),
    ("src/dm1v2/dm1_v2_settings_pc34.c", "V2 settings may scale/present that picture"),
    ("tests/test_dm1_v2_movement_viewport_pc34.c", "dm1_default_dungeon_dat_path"),
    ("tests/test_dm1_v2_movement_viewport_pc34.c", "_canonical/dm1/DUNGEON.DAT"),
]

FORBIDDEN_PRESENTATION_STATE_TOKENS = [
    "mapX",
    "mapY",
    "direction",
    "rawMapData",
    "DUNGEON",
    "squareFirstThing",
    "thing",
    "champion",
    "party",
]

FORBIDDEN_RENDERER_INCLUDES = [
    '#include "dm1_v2_movement_engine_pc34.h"',
    '#include "dm1_v2_movement_command_adapter_pc34.h"',
    '#include "dm1_v1_game_state_pc34_compat.h"',
]

errors: list[str] = []


def require(condition: bool, message: str) -> None:
    if not condition:
        errors.append(message)


def read_text(path: Path) -> str:
    if not path.exists():
        errors.append(f"missing file: {path}")
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def struct_body(text: str, struct_name: str) -> str:
    pattern = re.compile(r"typedef\s+struct\s*\{(?P<body>[^{}]*)\}\s*" + re.escape(struct_name) + r"\s*;", re.S)
    match = pattern.search(text)
    if not match:
        errors.append(f"missing typedef struct {struct_name}")
        return ""
    return match.group("body")


def check_originals() -> list[dict[str, str | int]]:
    anchors = []
    require(DM1_CANONICAL.exists(), f"missing canonical DM1 anchor directory: {DM1_CANONICAL}")
    for name, expected in EXPECTED_DM1_SHA256.items():
        path = DM1_CANONICAL / name
        require(path.exists(), f"missing canonical DM1 anchor: {path}")
        if path.exists():
            actual = sha256_file(path)
            size = path.stat().st_size
            require(actual == expected, f"{name} sha256 mismatch: {actual} != {expected}")
            anchors.append({"name": name, "path": str(path), "bytes": size, "sha256": actual})
    return anchors


def check_redmcsb() -> list[dict[str, object]]:
    require(REDMCSB.exists(), f"missing ReDMCSB source root: {REDMCSB}")
    verified = []
    for anchor in REDMCSB_ANCHORS:
        path = REDMCSB / str(anchor["file"])
        text = read_text(path)
        missing = [needle for needle in anchor["needles"] if needle not in text]
        require(not missing, f"{anchor['file']} {anchor['function']} missing markers: {missing}")
        verified.append({
            "file": anchor["file"],
            "function": anchor["function"],
            "lineRange": anchor["lineRange"],
            "why": anchor["why"],
            "markers": list(anchor["needles"]),
        })
    return verified


def check_firestaff() -> dict[str, object]:
    files_seen = sorted(set(path for path, _needle in FIRESTAFF_REQUIRED))
    file_texts = {rel: read_text(ROOT / rel) for rel in files_seen}
    for rel, needle in FIRESTAFF_REQUIRED:
        require(needle in file_texts[rel], f"missing Firestaff marker in {rel}: {needle}")

    header = file_texts["include/dm1_v2_viewport_renderer_pc34.h"]
    renderer = file_texts["src/dm1v2/dm1_v2_viewport_renderer_pc34.c"]
    settings = file_texts["src/dm1v2/dm1_v2_settings_pc34.c"]

    vp_state = struct_body(header, "DM1_V2_ViewportState")
    require("framebuffer[DM1_V2_VIEWPORT_H][DM1_V2_VIEWPORT_W]" in vp_state, "DM1_V2_ViewportState does not own a 224x136 presentation framebuffer")
    for token in FORBIDDEN_PRESENTATION_STATE_TOKENS:
        require(token not in vp_state, f"DM1_V2_ViewportState leaks gameplay token: {token}")

    v21_state = struct_body(renderer, "V21_ViewportState")
    require("v1_framebuffer[V21_SCREEN_W * V21_SCREEN_H]" in v21_state, "V21_ViewportState does not keep the V1 indexed framebuffer seam")
    require("palette[256]" in v21_state, "V21_ViewportState does not keep palette mapping as a separate presentation input")
    for token in FORBIDDEN_PRESENTATION_STATE_TOKENS:
        require(token not in v21_state, f"V21_ViewportState leaks gameplay token: {token}")
    for include in FORBIDDEN_RENDERER_INCLUDES:
        require(include not in renderer, f"V2 viewport renderer includes gameplay/movement boundary: {include}")

    require("dm1_v2_settings_apply_v21_presentation_defaults" in settings, "missing V2.1 presentation defaults helper")
    require("settings->palette_enhanced = 0" in settings, "V2.1 defaults do not preserve original VGA palette by default")
    require("settings->use_bilinear = 0" in settings, "V2.1 defaults should not bilinear-filter indexed source pixels")

    return {
        "checkedFiles": files_seen,
        "presentationStateIsolation": {
            "DM1_V2_ViewportStateForbiddenTokens": FORBIDDEN_PRESENTATION_STATE_TOKENS,
            "V21_ViewportStateForbiddenTokens": FORBIDDEN_PRESENTATION_STATE_TOKENS,
            "forbiddenRendererIncludes": FORBIDDEN_RENDERER_INCLUDES,
        },
    }


def main() -> int:
    originals = check_originals()
    redmcsb = check_redmcsb()
    firestaff = check_firestaff()
    result = {
        "status": "failed" if errors else "passed",
        "scope": "DM1 V2 Phase 2 graphics pipeline source isolation",
        "dm1Originals": originals,
        "redmcsbSourceRoot": str(REDMCSB),
        "redmcsbAnchors": redmcsb,
        "firestaffChecks": firestaff,
        "claim": "V2 presentation can scale/filter/present source DM1 graphics, palette, font metrics, and viewport geometry without storing gameplay state in presentation buffers/config.",
        "errors": errors,
    }
    VERIFY_OUT.parent.mkdir(parents=True, exist_ok=True)
    VERIFY_OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if errors:
        for error in errors:
            print(f"error: {error}")
        print(f"evidence={VERIFY_OUT.relative_to(ROOT)}")
        return 1
    print(f"dm1_v2_graphics_pipeline_source_isolation: ok evidence={VERIFY_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
